### ISSUE TITLE
🐛 [readarr] addon not starting

### ISSUE THREAD

**Issue by PubDeer** [alexbelgium/hassio-addons#1083]
### Description

Readarr gives an error after installing and opening. I'm on a Home Assistant Yellow and this is my first time using HA, so please forgive me if I made any obvious errors.

### Reproduction steps

```bash
1. Install add-on
2. Start add-on
3. Check the log
```

### Addon Logs

```bash
Starting...
/etc/cont-init.d/00-banner.sh: executing

-----------------------------------------------------------
 Add-on: Readarr
 Book manager and automation
-----------------------------------------------------------
 Add-on version: 0.3.10.2287-5
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.1  (aarch64 / yellow)
 Home Assistant Core: 2023.11.2
 Home Assistant Supervisor: 2023.11.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
 Defining permissions for main user : 
User UID: 0
User GID : 0
-----------------------------------------------------------
/etc/cont-init.d/00-config_location.sh: executing
[20:51:44] INFO: Config stored in /config/addons_config/readarr
sed: /etc/services.d/readarr/run: No such file or directory
Error : /etc/cont-init.d/00-config_location.sh exiting 1
/etc/cont-init.d/00-global_var.sh: executing
CONFIG_LOCATION='/config/addons_config/readarr'
PGID='0'
PUID='0'
/etc/cont-init.d/00-local_mounts.sh: executing
/etc/cont-init.d/00-smb_mounts.sh: executing
/etc/cont-init.d/01-config_yaml.sh: executing
Watch-out: your CONFIG_LOCATION should end by config.yaml, and instead it is readarr
Load environment variables from /config/addons_config/readarr if existing
---------------------------------------------------------
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables
... no config file, creating one from template. Please customize the file in /config/addons_config/readarr before restarting.
curl: (23) Failure writing output to destination
Error : /etc/cont-init.d/01-config_yaml.sh exiting 23
/etc/cont-init.d/01-custom_script.sh: executing
Execute /config/addons_autoscripts/readarr-nas.sh if existing
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation
---------------------------------------------------------
... no script found, exiting
/etc/cont-init.d/20-folders.sh: executing
/etc/cont-init.d/32-nginx_ingress.sh: executing
[20:51:47] WARNING: ---------------------------
[20:51:47] WARNING: Ingress is enabled, authentification will be disabled and should be managed through HA itself. If you need authentification, please disable ingress in addon options
[20:51:47] WARNING: ---------------------------
/etc/cont-init.d/90-disable_ingress.sh: executing
 
Starting the upstream container
 
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
```

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, perhaps i'll need to adapt this add-on! Have you tried starting a second time? The first start basically installs a config.yaml file in /config/addons_config/readarr then stops the add-on. Thanks!

**Comment by PubDeer** [comment]
Hi! Thanks for your swift response. I have tried a couple of stops/starts and also reinstalls. But the error persists. I installed Filebrowser and there is no readarr folder found in /config/addons_config

**Comment by airtonix** [comment]
same here, probably different error, but did : 

1. install addon
2. click start
3. check logs... 
4. open web ui

and i get a black screen with black text:

```
{
  "message": "Requested value \u0027external\u0027 was not found.",
  "description": "System.ArgumentException: Requested value \u0027external\u0027 was not found.\n   at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan\u00601 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64\u0026 result)\n   at System.Enum.TryParse(Type enumType, ReadOnlySpan\u00601 value, Boolean ignoreCase, Boolean throwOnFailure, Object\u0026 result)\n   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)\n   at NzbDrone.Core.Configuration.ConfigFileProvider.GetValueEnum[T](String key, T defaultValue, Boolean persist) in ./api/hassio_ingress/rxQdkphP9DRvsZ-eOsA7IT8nVPpZ2a3Drv2Ap3UdUD8/readarr.Core/Configuration/ConfigFileProvider.cs:line 258\n   at NzbDrone.Core.Configuration.ConfigFileProvider.get_AuthenticationMethod() in ./api/hassio_ingress/rxQdkphP9DRvsZ-eOsA7IT8nVPpZ2a3Drv2Ap3UdUD8/readarr.Core/Configuration/ConfigFileProvider.cs:line 189\n   at NzbDrone.Http.Authentication.UiAuthorizationPolicyProvider.GetPolicyAsync(String policyName) in ./api/hassio_ingress/rxQdkphP9DRvsZ-eOsA7IT8nVPpZ2a3Drv2Ap3UdUD8/readarr.Http/Authentication/UiAuthorizationPolicyProvider.cs:line 31\n   at Microsoft.AspNetCore.Authorization.AuthorizationPolicy.CombineAsync(IAuthorizationPolicyProvider policyProvider, IEnumerable\u00601 authorizeData)\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.\u003CInvoke\u003Eg__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)"
}
```

**Comment by airtonix** [comment]
> config.yaml file in /config/addons_config/readarr t

This is also a problem since what it actually does is create a directory called `/config/addons_config/readarr/config.yaml` which contains the `config.xml`.

So on first install this fails, because readarr actually wants: `/config/addons_config/readarr/config.xml`, but instead this is stored at `/config/addons_config/readarr/config.yaml/config.xml`

**Comment by alexbelgium** [comment]
Thanks, I've pushed a new version that should solve this

**Comment by PubDeer** [comment]
```Current version: 0.3.10.2287-10```

Thanks! The newest version no longer gives errors in the log. However, I do still get this error when opening the WEB-UI. Also, there is still no folder/file created in config/addons_config for me.

```{
  "message": "Requested value \u0027external\u0027 was not found.",
  "description": "System.ArgumentException: Requested value \u0027external\u0027 was not found.\n   at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan\u00601 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64\u0026 result)\n   at System.Enum.TryParse(Type enumType, ReadOnlySpan\u00601 value, Boolean ignoreCase, Boolean throwOnFailure, Object\u0026 result)\n   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)\n   at NzbDrone.Core.Configuration.ConfigFileProvider.GetValueEnum[T](String key, T defaultValue, Boolean persist) in ./api/hassio_ingress/4_ENFUhIqrpWc-cdDVOmBTEuzIYBFnhq684fJ55cIKA/readarr.Core/Configuration/ConfigFileProvider.cs:line 258\n   at NzbDrone.Core.Configuration.ConfigFileProvider.get_AuthenticationMethod() in ./api/hassio_ingress/4_ENFUhIqrpWc-cdDVOmBTEuzIYBFnhq684fJ55cIKA/readarr.Core/Configuration/ConfigFileProvider.cs:line 189\n   at NzbDrone.Http.Authentication.UiAuthorizationPolicyProvider.GetPolicyAsync(String policyName) in ./api/hassio_ingress/4_ENFUhIqrpWc-cdDVOmBTEuzIYBFnhq684fJ55cIKA/readarr.Http/Authentication/UiAuthorizationPolicyProvider.cs:line 31\n   at Microsoft.AspNetCore.Authorization.AuthorizationPolicy.CombineAsync(IAuthorizationPolicyProvider policyProvider, IEnumerable\u00601 authorizeData)\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.\u003CInvoke\u003Eg__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)"```

**Comment by alexbelgium** [comment]
Hi, I've pushed a version 11 to avoid the error you have encountered. Could you please after updating post your full log? It's strange that the folders doesn't get created if readarr still detects that the "external" setting is defined. Thanks!

**Comment by alexbelgium** [comment]
Mmh strange... do you have the config.xml in /config/addons_config/readarr ? Can you stop the addon, remove the line containing "external" then restart ?

**Comment by PubDeer** [comment]
There is nothing related to readarr in /config/addons_config/. Only folder I have in there is filebrowser, which I installed to be able to investigate the errors I got with readarr. Would a reinstall help? Or is stopping/starting sufficient?

**Comment by alexbelgium** [comment]
Hi see, you need to blame HA devs ;-) with the new logic of mounting addons, the /config folder is actually now mounted in /homeassistant.

So in filebrowser you'll find the folder in /homeassistant/addons_config/readarr...

Sorry for the confusion, I'm not the one having defined that ;-) : https://github.com/alexbelgium/hassio-addons/blob/master/filebrowser/CHANGELOG.md#2230_reverted5-21-11-2023

**Comment by PubDeer** [comment]
Hi - I'm sorry! Didn't realize I was looking in the wrong /addons_config/ folder. Your suggestion fixed the problem - so stopping, deleting the line and starting again. Thank you for your excellent help, I'll be sure to buy you a cup of coffee :)

**Comment by alexbelgium** [comment]
Thanks very much ! Happy it works!
