### ISSUE TITLE
🐛 [Nextcloud] New installation won't start

### ISSUE THREAD

**Issue by Holger-H** [alexbelgium/hassio-addons#1170]
### Description

After installing Nextcloud 28.0.1-2 Addon it won't start and Nextcloud UI shows error (ERR_CONNECTION_REFUSED).

### Reproduction steps

```bash
1. Install Nextcloud 28.0.1 Addon
2. Start Addon and complete initial setup of Nextcloud 
3. Update Nextcloud 28.0.1 Addon to 28.0.1-2
4. May do something in your Nextcloud instance
5. Uninstall Nextcloud Addon (config was just for test, uninstall)
6. Delete Folder share/nextcloud
7. Install Nextcloud Addon
8. Start Addon
9. Nextcloud UI won't show anything
10. Wait some hours -> nothing changes
```

### Addon Logs

```bash
Starting...
/etc/cont-init.d/00-banner.sh: executing

-----------------------------------------------------------
 Add-on: Nextcloud
 Nextcloud for Homeassistant
-----------------------------------------------------------
 Add-on version: 28.0.1-2
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.4  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.1.2
 Home Assistant Supervisor: 2023.12.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
 Defining permissions for main user : 
User UID: 1000
User GID : 1000
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
Full_Text_Search='false'
OCR='false'
OCRLANG='fra'
PGID='1000'
PUID='1000'
additional_apps='inotify-tools'
certfile='fullchain.pem'
elasticsearch_server='<ip:port>'
enable_thumbnails='true'
keyfile='privkey.pem'
trusted_domains='your-domain, your-domain2'
use_own_certs='false'
/etc/cont-init.d/00-local_mounts.sh: executing
/etc/cont-init.d/00-smb_mounts.sh: executing
/etc/cont-init.d/01-config_yaml.sh: executing
Setting permissions for the config.yaml directory

Load environment variables from /config/addons_config/nextcloud-ocr/config.yaml if existing
If accessing the file with filebrowser it should be mapped to /homeassistant/addons_config/nextcloud-ocr/config.yaml
---------------------------------------------------------
Wiki here on how to use : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables

... no env variables found, exiting
/etc/cont-init.d/01-custom_script.sh: executing
Execute /homeassistant/addons_config/nextcloud-ocr/nextcloud-ocr.sh if existing
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation
/etc/cont-init.d/01-folders.sh: executing
Setting user to 1000:1000
Updating permissions...
... Config directory : /data
... data directory detected : /share/nextcloud
... setting permissions
... done
 
/etc/cont-init.d/02-init_steps.sh: executing
/etc/cont-init.d/02-mariadb_discovery.sh: executing
/etc/cont-init.d/30-ssl.sh: executing
/etc/cont-init.d/99-add_packages.sh: executing
/etc/cont-init.d/99-elasticsearch.sh: executing
/etc/cont-init.d/99-ocr.sh: executing
/etc/cont-init.d/99-trusted_domains.sh: executing
 
Starting the upstream container
 
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

using keys found in /data/config/keys
Initializing nextcloud 28.0.1.1 (this can take a while) ...
Setting permissions
New nextcloud instance
Please run the web-based installer on first connect!
Initializing finished
After completing the web-based installer, restart the Nextcloud container to apply default memory caching and transactional file locking configurations.
Alternatively, you can apply your own configurations by editing /data/config/www/nextcloud/config/config.php following the documentation:
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/caching_configuration.html
https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/files_locking_transactional.html
Starting...
/etc/cont-init.d/02-init_steps.sh: executing
Setting logs
... checking for app updates
Nextcloud is not installed - only a limited number of commands are available

                                                         
  There are no commands defined in the "app" namespace.  
                                                         

Error : /etc/cont-init.d/02-init_steps.sh exiting 1
/etc/cont-init.d/02-mariadb_discovery.sh: executing
/etc/cont-init.d/99-add_packages.sh: executing
[17:52:08] INFO: Installing additional apps :
... inotify-tools
/etc/cont-init.d/99-elasticsearch.sh: executing
/etc/cont-init.d/99-ocr.sh: executing
/etc/cont-init.d/99-trusted_domains.sh: executing
[17:52:12] INFO: Currently set trusted domains :
Nextcloud is not installed - only a limited number of commands are available

                                                                   
  There are no commands defined in the "config:system" namespace.  
                                                                   

[17:52:12] INFO: No trusted domain set yet. The first one will be set when doing initial configuration
[17:52:12] INFO: Trusted domains set in the configuration. Refreshing domains.
[17:52:12] INFO: ... removing previously added trusted domain (except for first one created)
Nextcloud is not installed - only a limited number of commands are available

                                                                   
  There are no commands defined in the "config:system" namespace.  
                                                                   

Error : /etc/cont-init.d/99-trusted_domains.sh exiting 1
 
Starting the upstream container
 
[custom-init] No custom files found, skipping...
crond: crond (busybox 1.36.1) started, log level 8
[ls.io-init] done.
[10-Jan-2024 17:52:13] NOTICE: fpm is running, pid 984
[10-Jan-2024 17:52:13] NOTICE: ready to handle connections
crond: USER abc pid 1292 cmd /usr/bin/php /app/www/public/cron.php 2>&1
Exception: Not installed in /app/www/public/lib/base.php:283
Stack trace:
#0 /app/www/public/lib/base.php(709): OC::checkInstalled()
#1 /app/www/public/lib/base.php(1200): OC::init()
#2 /app/www/public/cron.php(43): require_once('...')
#3 {main}
Exception: Not installed in /app/www/public/lib/base.php:283
Stack trace:
#0 /app/www/public/lib/base.php(709): OC::checkInstalled()
#1 /app/www/public/lib/base.php(1200): OC::init()
#2 /app/www/public/cron.php(43): require_once('...')
#3 {main}
```

### Architecture

aarch64

### OS

HAos

**Comment by jonnyrider** [comment]
I'm having the same issue after the fix you tried! Any to help with any troubleshooting. The port is open on the server when using Nmap, so something is getting through.

**Comment by alexbelgium** [comment]
After the "fix" you have the issue? or were you having it before alors?

**Comment by jonnyrider** [comment]
I only installed it for the first time yesterday morning, and I had the
issue where I coudn't access the web interface. Updated last night, but
still have the issue.

**Comment by alexbelgium** [comment]
Thanks ; I'll try on a VM to have a blank system

**Comment by alexbelgium** [comment]
Would you have a log with the latest version? it should in theory avoid the error message in the first log, thanks

**Comment by jonnyrider** [comment]
Here you go:

```
Starting...
/etc/cont-init.d/00-banner.sh: executing

-----------------------------------------------------------
 Add-on: Nextcloud
 Nextcloud for Homeassistant
-----------------------------------------------------------
 Add-on version: 28.0.1-3
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.4  (amd64 / qemux86-64)
 Home Assistant Core: 2024.1.2
 Home Assistant Supervisor: 2023.12.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
 Defining permissions for main user : 
User UID: 1000
User GID : 1000
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
Full_Text_Search='false'
OCR='false'
OCRLANG='eng'
PGID='1000'
PUID='1000'
additional_apps='inotify-tools'
certfile='fullchain.pem'
elasticsearch_server='<ip:port>'
enable_thumbnails='true'
keyfile='privkey.pem'
trusted_domains='192.168.0.167'
use_own_certs='false'
/etc/cont-init.d/00-local_mounts.sh: executing
/etc/cont-init.d/00-smb_mounts.sh: executing
/etc/cont-init.d/01-config_yaml.sh: executing
Setting permissions for the config.yaml directory
Load environment variables from /config/addons_config/nextcloud-ocr/config.yaml if existing
If accessing the file with filebrowser it should be mapped to /homeassistant/addons_config/nextcloud-ocr/config.yaml
---------------------------------------------------------
Wiki here on how to use : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables


... no env variables found, exiting
/etc/cont-init.d/01-custom_script.sh: executing
Execute /homeassistant/addons_config/nextcloud-ocr/nextcloud-ocr.sh if existing
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation
/etc/cont-init.d/01-folders.sh: executing
Setting user to 1000:1000
Updating permissions...
... Config directory : /data
... data directory detected : /share/nextcloud
... setting permissions
... done
 
/etc/cont-init.d/02-init_steps.sh: executing
/etc/cont-init.d/02-mariadb_discovery.sh: executing
/etc/cont-init.d/30-ssl.sh: executing
/etc/cont-init.d/99-add_packages.sh: executing
/etc/cont-init.d/99-elasticsearch.sh: executing
/etc/cont-init.d/99-ocr.sh: executing
/etc/cont-init.d/99-trusted_domains.sh: executing
 
Starting the upstream container
 
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

using keys found in /data/config/keys
Initializing nextcloud 28.0.1.1 (this can take a while) ...
Setting permissions
New nextcloud instance
Please run the web-based installer on first connect!
Initializing finished
After completing the web-based installer, restart the Nextcloud container to apply default memory caching and transactional file locking configurations.
Alternatively, you can apply your own configurations by editing /data/config/www/nextcloud/config/config.php following the documentation:
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/caching_configuration.html
https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/files_locking_transactional.html
Starting...
/etc/cont-init.d/02-init_steps.sh: executing
Setting logs
 
--------------------------------------------------------------------------------------------------------------
Nextcloud not installed, please wait for addon startup, login Webui, install Nextcloud, then restart the addon
--------------------------------------------------------------------------------------------------------------
 
/etc/cont-init.d/02-mariadb_discovery.sh: executing
---
MariaDB addon was found! It can't be configured automatically due to the way Nextcloud works, but you can configure it manually when running the web UI for the first time using those values :
Database user : service bashio::log.blue Database user : service
Database password : nohTheatuij8Diengoom0ahm5PaePha8phux2ar8xo1Vaja6xies2Cha9yietei0
Database name : nextcloud
Host-name : core-mariadb:3306
---
/etc/cont-init.d/99-add_packages.sh: executing
[15:23:20] INFO: Installing additional apps :
... inotify-tools
/etc/cont-init.d/99-elasticsearch.sh: executing
/etc/cont-init.d/99-ocr.sh: executing
/etc/cont-init.d/99-trusted_domains.sh: executing
 
Starting the upstream container
 
[custom-init] No custom files found, skipping...
crond: crond (busybox 1.36.1) started, log level 8
[ls.io-init] done.
[11-Jan-2024 15:23:22] NOTICE: fpm is running, pid 977
[11-Jan-2024 15:23:22] NOTICE: ready to handle connections
```

After a few minutes:

```
crond: USER abc pid 1183 cmd /usr/bin/php /app/www/public/cron.php 2>&1
Exception: Not installed in /app/www/public/lib/base.php:283
Stack trace:
#0 /app/www/public/lib/base.php(709): OC::checkInstalled()
#1 /app/www/public/lib/base.php(1200): OC::init()
#2 /app/www/public/cron.php(43): require_once('...')
#3 {main}
Exception: Not installed in /app/www/public/lib/base.php:283
Stack trace:
#0 /app/www/public/lib/base.php(709): OC::checkInstalled()
#1 /app/www/public/lib/base.php(1200): OC::init()
#2 /app/www/public/cron.php(43): require_once('...')
#3 {main}
```

**Comment by alexbelgium** [comment]
Thanks ; I'll look to replicate on my VM

**Comment by alexbelgium** [comment]
Thanks I've pushed a new version please let me know how it goes!

**Comment by ymurawski** [comment]
After uninstall and re install its still hangs on start... but in the overview it says version 28.0.1-3 after fresh install but 28.0.1-4 is the new i think. how to update this ?


LOG:

/etc/cont-init.d/02-init_steps.sh: executing
/etc/cont-init.d/02-mariadb_discovery.sh: executing
/etc/cont-init.d/30-ssl.sh: executing
/etc/cont-init.d/99-add_packages.sh: executing
/etc/cont-init.d/99-elasticsearch.sh: executing
/etc/cont-init.d/99-ocr.sh: executing
/etc/cont-init.d/99-trusted_domains.sh: executing
 
Starting the upstream container
 
[migrations] started
[migrations] 01-nginx-site-confs-default: executing...
[migrations] 01-nginx-site-confs-default: succeeded
[migrations] 02-default-location: executing...
[migrations] 02-default-location: succeeded
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

Setting resolver to  127.0.0.11
Setting worker_processes to 4
generating self-signed keys in /data/config/keys, you can replace these with your own keys if required
........+.+............+++++++++++++++++++++++++++++++++++++++*....+.+.....+...+.+.........+..+...+++++++++++++++++++++++++++++++++++++++*......+.+..+...+.+....................+.+...+..+....+...+...+..+......+.+.........+.........+..+..........+...........+...+.+.........+.............................+.+..+....+......+..+..........+...........+......+...+.++++++
...+.........+....+..+++++++++++++++++++++++++++++++++++++++*...+.....+....+...+..+....+..+.........+.+.........+.....+...+.............+...............+++++++++++++++++++++++++++++++++++++++*..+.....+..........+.....+....+..+......+...+......+....+...........+.+..+.+......+.........+..+..........+...+.....+.+......+..+......+...................+........+..........+...+..+...+......+....+.........+..+....+.........+...+..+......................+.....+.+.....+...+.+..............+............+.........+...+...+...............+.......+...+..+.+....................+.......+...+..+.......+...+..+.......+.........+.....+......+...+.+..+.........+....+.........+......+......+......+........+......+...+..........+..............................+..+.+...+..+.........+.........+....+.....+.......+...+...+...............+..+...+....+......+............+..+.............+...+..+.+..............+...+...+.+...+...............+..+...+.+...............+..+...+.......+........+......+.+...+............+...+......+........+..........+....................+.............+........+.+........+...+.......+...............+..+.+..+.......+...+......+..............+...+.........+.+...+.....+......+.+.....+.........+...+..........+......+.................+.........+..........+...++++++
-----
Initializing nextcloud 28.0.1.1 (this can take a while) ...
Setting permissions
New nextcloud instance
Please run the web-based installer on first connect!
Initializing finished
After completing the web-based installer, restart the Nextcloud container to apply default memory caching and transactional file locking configurations.
Alternatively, you can apply your own configurations by editing /data/config/www/nextcloud/config/config.php following the documentation:
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/caching_configuration.html
https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/files_locking_transactional.html
Starting...
/etc/cont-init.d/02-init_steps.sh: executing
Setting logs
 
--------------------------------------------------------------------------------------------------------------
Nextcloud not installed, please wait for addon startup, login Webui, install Nextcloud, then restart the addon
--------------------------------------------------------------------------------------------------------------
 
/etc/cont-init.d/02-mariadb_discovery.sh: executing
---
MariaDB addon was found! It can't be configured automatically due to the way Nextcloud works, but you can configure it manually when running the web UI for the first time using those values :
Database user : service bashio::log.blue Database user : service
Database password : ooghie1oangeexoefisi6foo6piwaht7Ohghaesoomooquiefei8ic9Chooqui5e
Database name : nextcloud
Host-name : core-mariadb:3306
---
/etc/cont-init.d/99-add_packages.sh: executing
Cloning into 'pdfannotate'...
warning: redirecting to https://gitlab.com/nextcloud-other/nextcloud-annotate.git/
Nextcloud annotate app added to Nextcloud app store
[13:04:15] INFO: Installing additional apps :
... inotify-tools
/etc/cont-init.d/99-elasticsearch.sh: executing
/etc/cont-init.d/99-ocr.sh: executing
/etc/cont-init.d/99-trusted_domains.sh: executing
 
Starting the upstream container
 
[custom-init] No custom files found, skipping...
crond: crond (busybox 1.36.1) started, log level 8
[ls.io-init] done.
[12-Jan-2024 13:04:16] NOTICE: fpm is running, pid 1011
[12-Jan-2024 13:04:16] NOTICE: ready to handle connections
crond: USER abc pid 1132 cmd /usr/bin/php /app/www/public/cron.php 2>&1
Exception: Not installed in /app/www/public/lib/base.php:283
Stack trace:
#0 /app/www/public/lib/base.php(709): OC::checkInstalled()
#1 /app/www/public/lib/base.php(1200): OC::init()
#2 /app/www/public/cron.php(43): require_once('...')
#3 {main}
Exception: Not installed in /app/www/public/lib/base.php:283
Stack trace:
#0 /app/www/public/lib/base.php(709): OC::checkInstalled()
#1 /app/www/public/lib/base.php(1200): OC::init()
#2 /app/www/public/cron.php(43): require_once('...')
#3 {main}

**Comment by ymurawski** [comment]
ok after refresh updates and install the new update and a reboot everything works now <3

**Comment by ymurawski** [comment]
When i first start and want to config the mariaDB it jumps right back to initial page where postsql is selected

![Bildschirm­foto 2024-01-12 um 13 36 43](https://github.com/alexbelgium/hassio-addons/assets/46036625/d4f9768e-16d1-49a2-bc9a-74cc43f44a66)
![Bildschirm­foto 2024-01-12 um 13 37 03](https://github.com/alexbelgium/hassio-addons/assets/46036625/1eb8cc4f-c0df-468d-aa19-14dea3da4855)

**Comment by Holger-H** [comment]
It works again. Thank you 👍

**Comment by alexbelgium** [comment]
> When i first start and want to config the mariaDB it jumps right back to initial page where postsql is selected

Not sure to understand in this screen you select your database info, the data location then click install ; watch out you can't change those values afterwards

**Comment by ymurawski** [comment]
> > When i first start and want to config the mariaDB it jumps right back to initial page where postsql is selected
> 
> Not sure to understand in this screen you select your database info, the data location then click install ; watch out you can't change those values afterwards

I selected Maria dB because it is installed on my HA. Like in the How to I added the credentials but it jumps right back to the next loud start clean like you start it for the first time. Seems it doesn't try to connect to the Maria dB

**Comment by alexbelgium** [comment]
Do you mean that you click on "install" and nothing happens? it doesn't show the install screen, then the dashboard?

**Comment by ymurawski** [comment]
Ohhhh shi**** I found the problem... The problem is behind the screen. I tried to add a user called admin... But the user already exists 🙈

**Comment by jonnyrider** [comment]
All working for me with the latest update. Thanks for the quick fix!

**Comment by alexbelgium** [comment]
Thanks all!
