### ISSUE TITLE
🐛 [INADYN] Addon not starting after update

### ISSUE THREAD

**Issue by kolossboss** [alexbelgium/hassio-addons#2161]
### Description

Inadyn is not starting after updated to v2.13.0.

No problem for months.
Thats my config:

```
providers:
  - hostname: xx.xxxx.de
    provider: cloudflare:1
    username: xxxx.de
    password: djchsnrkficxxxxxxxx
  - hostname: xxx.xxxx.de
    provider: cloudflare:2
    username: xxxx.de
    password: djchsnrkficxxxxxxxx
verify_address: false

```  

### Reproduction steps

```bash
1. Go to 'Addons'
2. Click on 'Inadyn and click start'
3. Scroll down to '....'
4. See error
```

### Addon Logs

```bash
-----------------------------------------------------------
 Add-on version: 2.13.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 16.2
 Architecture: amd64 / qemux86-64
 Home Assistant Core: 2025.10.4
 Home Assistant Supervisor: 2025.10.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
[07:51:06] WARNING: One of your option is an array, skipping
verify_address='false'
/etc/cont-init.d/01-config_yaml.sh: executing
...
/etc/cont-init.d/01-custom_script.sh: executing
...
/etc/cont-init.d/99-run.sh: executing
/etc/cont-init.d/99-run.sh: line 9: mustache-cli: command not found
Error : /etc/cont-init.d/99-run.sh exiting 127
Starting the upstream container
```

### Architecture

amd64

### OS

Virtual Machine

**Comment by rektosaure** [comment]
Can confirm this

**Comment by danielwernerio** [comment]
@alexbelgium Thank you for your effort, but the new image which should be located at:

`ghcr.io/alexbelgium/inadyn-aarch64:2.13.0-2`

isn't available. Therefore I get an error if I try to update Inadyn and the current version isn't working anymore..
Could you please fix this?

**Comment by alexbelgium** [comment]
Hi, I pushed a new version

**Comment by kolossboss** [comment]
New version can be installed now, but still not working. Same issue like OP.

Going back to 2.12.0-2 via backup restore and works fine again.

**Comment by alexbelgium** [comment]
Given the app is deprecated I've reverted to the previous version
