### ISSUE TITLE
[Calibre] Can't mount smb share

### ISSUE THREAD

**Issue by marlonqpa** [alexbelgium/hassio-addons#311]
**Which addon?**

- Addon name : Calibre
- Addon version : 5.38

**Describe the bug**

My mounts are on QNAP nas.  I tried different mounts from this nas, with different credentials. Always the same result.
Is the message _apt-get: command not found_ means my system is missing some dependencies?

**To Reproduce**

**Full addon log**

`
[cont-init.d] 92-local_mounts.sh: executing... 
[cont-init.d] 92-local_mounts.sh: exited 0.
[cont-init.d] 92-smb_mounts.sh: executing... 
Mounting smb share(s)...
[13:48:02] FATAL: Error, unable to mount //192.168.1.10/Multimedia to /mnt/Multimedia with username calibre, ***********. Please check your remote share path, username, password, domain, try putting 0 in UID and GID
[13:48:02] FATAL: Here is some debugging info :
/var/run/s6/etc/cont-init.d/92-smb_mounts.sh: line 75: apt-get: command not found
/var/run/s6/etc/cont-init.d/92-smb_mounts.sh: line 75: apk: command not found
[cont-init.d] 92-smb_mounts.sh: exited 127.
`

**Full addon config**

PGID: 0
PUID: 0
cifspassword: *******
cifsusername: calibre
networkdisks: //192.168.1.10/Multimedia
TZ: Europe/Warsaw

**System**

Home Assistant Core 2022.5.0b6
Home Assistant Supervisor 2022.05.0
Home Assistant OS 8.0.rc3
Kernel version 5.15.32-v8
Agent version 1.2.1
Hardware: RPi4

**Supervisor log**

`
22-05-03 13:47:53 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning addon_db21ed7f_calibre application
22-05-03 13:47:53 ERROR (SyncWorker_4) [supervisor.docker.addon] Add-on Calibre try to access to blocked device sda!
22-05-03 13:47:53 ERROR (SyncWorker_4) [supervisor.docker.addon] Add-on Calibre try to access to blocked device sda1!
22-05-03 13:47:54 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on ghcr.io/alexbelgium/calibre-aarch64 with version v5.38
`

**Comment by alexbelgium** [comment]
Hi, thanks I think I see the issue. It uses pacman which I had not included in this script, I'll do an update

**Comment by alexbelgium** [comment]
Hi, it is solved in the new version pushed :-)

**Comment by marlonqpa** [comment]
Hi

Unfortunately, after update to the most recent version (5.38-3) I've got still the same error.

**Comment by alexbelgium** [comment]
Mmh weird I thought I could replicate it (it couldn't mount before then I added permissions and now itncan mount). I'll try again.

**Comment by alexbelgium** [comment]
Indeed I've checked again and smb mount works now, and I've got the same me config as you. Since v3 I've dded the required permissions so I m quite confident that it should work. Are you sure that your share is //ip/multimedia and not that there is another layer of folder, and that the case is correct? Thanks

**Comment by marlonqpa** [comment]
You are right, it's my fault. On different credential is working fine now.

**Comment by alexbelgium** [comment]
Thanks for the feedback!
