### ISSUE TITLE
🐛 [Transmission Openvpn] Transmission client is killed upon VPN restart (because of inactivity)

### ISSUE THREAD

**Issue by almico** [alexbelgium/hassio-addons#435]
**Which addon?**

- Addon name : Transmission Openvpn
- Addon version : 4.0-v10

**Describe the bug**

When the VPN tries to restart, everything is taken down.

**To Reproduce**

Wait for the VPN to restart.

**Full addon log**

I'm pasting the relevant part of the log. I can post the beginning, if needed.

```
[22/Aug/2022:14:09:08 +0200] 200 192.168.16.2, 172.30.32.1(172.30.32.2) POST /rpc HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36)
Mon Aug 22 14:16:26 2022 [xyz.somevpn.com] Inactivity timeout (--ping-restart), restarting
Mon Aug 22 14:16:26 2022 SIGTERM received, sending exit notification to peer
Mon Aug 22 14:16:27 2022 /etc/openvpn/tunnelDown.sh tun0 1500 1585 10.8.3.2 255.255.255.0 init
resolv.conf was restored
Sending kill signal to transmission-daemon
Waiting 5s for transmission-daemon to die
Sending kill signal (SIGKILL) to transmission-daemon
Mon Aug 22 14:16:30 2022 /sbin/ip route del [redacted]/32
Mon Aug 22 14:16:30 2022 /sbin/ip route del 0.0.0.0/1
Mon Aug 22 14:16:30 2022 /sbin/ip route del 128.0.0.0/1
Mon Aug 22 14:16:30 2022 Closing TUN/TAP interface
Mon Aug 22 14:16:30 2022 /sbin/ip addr del dev tun0 10.8.3.2/24
Mon Aug 22 14:16:30 2022 SIGTERM[soft,exit-with-notification] received, process exiting
2022/08/22 14:22:48 [error] 720#720: *3726 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: db21ed7f-transmission-openvpn, request: "GET /web/tr-web-control/script/easyui/locale/easyui-lang-en.js?_=1661170966625 HTTP/1.1", upstream: "http://127.0.0.1:9091/transmission/web/tr-web-control/script/easyui/locale/easyui-lang-en.js?_=1661170966625", host: "192.168.16.103:8123", referrer: "http://192.168.16.103:8123/api/hassio_ingress/fA4Z8Xm1mGT71HBH5mm9EYeMk4T-A9z2ElJhC7rpKYI/web/"
[22/Aug/2022:14:22:48 +0200] 502 192.168.16.2, 172.30.32.1(172.30.32.2) GET /web/tr-web-control/script/easyui/locale/easyui-lang-en.js?_=1661170966625 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36)
2022/08/22 14:22:48 [error] 720#720: *3726 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: db21ed7f-transmission-openvpn, request: "GET /web/tr-web-control/script/easyui/locale/easyui-lang-en.js?_=1661170966626 HTTP/1.1", upstream: "http://127.0.0.1:9091/transmission/web/tr-web-control/script/easyui/locale/easyui-lang-en.js?_=1661170966626", host: "192.168.16.103:8123", referrer: "http://192.168.16.103:8123/api/hassio_ingress/fA4Z8Xm1mGT71HBH5mm9EYeMk4T-A9z2ElJhC7rpKYI/web/"
[22/Aug/2022:14:22:48 +0200] 502 192.168.16.2, 172.30.32.1(172.30.32.2) GET /web/tr-web-control/script/easyui/locale/easyui-lang-en.js?_=1661170966626 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36)
```

**Full addon config**

```
DEBUG: false
DNS_server: 8.8.4.4,1.1.1.1
LOCAL_NETWORK: 192.168.0.0/16
OPENVPN_PASSWORD: [redacted]
OPENVPN_USERNAME: [redacted]
PGID: "1000"
PUID: "1000"
TRANSMISSION_DOWNLOAD_DIR: /mnt/shared/transmission/downloads
TRANSMISSION_HOME: /config/addons_config/transmission
TRANSMISSION_INCOMPLETE_DIR: /mnt/shared/transmission/incomplete
TRANSMISSION_WATCH_DIR: /mnt/shared/transmission/watch_dir
TRANSMISSION_WEB_UI: transmission-web-control
OPENVPN_CUSTOM_PROVIDER: true
OPENVPN_CUSTOM_PROVIDER_OVPN_LOCATION: [redacted]
TRANSMISSION_V3_UPDATE: true
cifspassword: [redacted]
cifsusername: [redacted]
networkdisks: //192.168.16.18/shared
```

**System**

- Supervisor version: 2022.08.3
- Host system version: 8.4

**Comment by alexbelgium** [comment]
Hi, is this a new behavior ? As this seems an upstream behavior. Or it is due to the "latest" image and I'll revert to the "4.0" one. Thanks

**Comment by almico** [comment]
I can't answer with absolute certainty. I moved from a Raspberry PI 4B to a VM inside an Intel i5. All I know is I faced it today for the first time 😃

**Comment by alexbelgium** [comment]
Do you have a custom config file for which you could remove the ’--ping-restart‘ directive that is mentioned at the top of your excerpt?

**Comment by almico** [comment]
Do you want me to try deleting it? As far as I remember, it's set by the VPN provider in its config.

**Comment by almico** [comment]
The very same issue happened with "4.0-v17".
I'm going to upgrade to "4.0-v18" and see what happens.

**Comment by almico** [comment]
This issue is still there, using 4.0-v19

**Comment by alexbelgium** [comment]
Thanks ; however I honestly have no idea of what could help. I could revert the image back to 4.0 instead of latest if you'd prefer

**Comment by almico** [comment]
If I got it correctly, in `/etc/cont-init.d/99-run.sh` you execute `/./etc/openvpn/start.sh & echo ""`.
That script, in turn, executes `exec openvpn ${TRANSMISSION_CONTROL_OPTS} ${OPENVPN_OPTS} --config "${CHOSEN_OPENVPN_CONFIG}"` that, I think, triggers `tunnelUp.sh`.
So far, everything is ok.
The problem should be that openvpn is shut down either because of some inactivity timeout, or because of an explicit (remote?) reset request. That triggers the execution of `tunnelDown.sh`, and that's the end of the story 😄 
All that should be needed is a restart of openvpn (a new `exec openvpn...`?). Maybe from within `tunnelDown.sh`?

**Comment by alexbelgium** [comment]
Hi, this looks like https://github.com/haugene/docker-transmission-openvpn/issues/2063

**Comment by alexbelgium** [comment]
Thanks for the analysis, I've replaced the tunnel own script by an automatic addon restart. This is comparable to openvpn restart but avoids deal g with potential network issues. Could you please test? Thanks!

**Comment by almico** [comment]
Upgrading now 😃

**Comment by almico** [comment]
@alexbelgium 
There must be a bug in the "resurrect" script 😄 

```
Mon Sep 19 18:17:39 2022 [antanex.com] Inactivity timeout (--ping-restart), restarting
Mon Sep 19 18:17:39 2022 SIGTERM received, sending exit notification to peer
Mon Sep 19 18:17:40 2022 /etc/openvpn/tunnelDown.sh tun0 1500 1585 10.8.1.3 255.255.255.0 init
parse error: Expected string key before ':' at line 1, column 4
[16:17:40] ERROR: Unknown HTTP error occured
Mon Sep 19 18:17:40 2022 WARNING: Failed running command (--up/--down): external program exited with error status: 1
Mon Sep 19 18:17:40 2022 Exiting due to fatal error
```

The only option, for me, is manually restart the addon.

**Comment by alexbelgium** [comment]
Hi, I've pushed a new version, could you please test it? Thankw

**Comment by almico** [comment]
Thank you. I upgraded last night.
Will post findings 😃

**Comment by almico** [comment]
Hi @alexbelgium 😃 
Unfortunately, the issue is still there:

```
Wed Oct 12 02:08:41 2022 [somevpn.org] Inactivity timeout (--ping-restart), restarting
Wed Oct 12 02:08:41 2022 SIGTERM received, sending exit notification to peer
Wed Oct 12 02:08:42 2022 /etc/openvpn/tunnelDown.sh tun0 1500 1585 10.8.0.4 255.255.255.0 init
parse error: Expected string key before ':' at line 1, column 4
[00:08:42] ERROR: Unknown HTTP error occured
Wed Oct 12 02:08:42 2022 WARNING: Failed running command (--up/--down): external program exited with error status: 1
Wed Oct 12 02:08:42 2022 Exiting due to fatal error
```

The only option is a manual restart.

**Comment by alexbelgium** [comment]
You could try to check the content of the /etc/openvpn/tunnelDown.sh file using portainer. If I find some time I'll reinstall the addon to test

**Comment by almico** [comment]
I already looked at that file, but it makes no sense to me. If I execute it manually, it succeeds, but this is true while everything is working fine.
My best guess is that script is executed in a different system state, and, most likely, it is some other script that is, called by it, failing. In other words, I fear the "parse error" is not coming directly from /etc/openvpn/tunnelDown.sh, but from, say `bashio::addon.restart`.

**Comment by alexbelgium** [comment]
Hi, please try this version I've added api access to see if it changes anything

**Comment by almico** [comment]
Will report as soon as anything relevant happens 😃

**Comment by almico** [comment]
```
Thu Oct 13 16:46:18 2022 [somevpn.org] Inactivity timeout (--ping-restart), restarting
Thu Oct 13 16:46:18 2022 SIGTERM received, sending exit notification to peer
Thu Oct 13 16:46:19 2022 /etc/openvpn/tunnelDown.sh tun0 1500 1585 10.8.2.2 255.255.255.0 init
parse error: Expected string key before ':' at line 1, column 4
[14:46:19] ERROR: Unknown HTTP error occured
Thu Oct 13 16:46:19 2022 WARNING: Failed running command (--up/--down): external program exited with error status: 1
Thu Oct 13 16:46:19 2022 Exiting due to fatal error
```

Same as before. I really cannot understand in what file is expected to be that ":" at line 1, column 4 😭

**Comment by alexbelgium** [comment]
I wonder if this is because the bashio command requires root, and the script is launcher from a user... I think it means it can't read the options.json file, which requires root access

**Comment by almico** [comment]
Some result, different error message, this time:

```
Sun Oct 16 02:43:32 2022 [somevpn.org] Inactivity timeout (--ping-restart), restarting
Sun Oct 16 02:43:32 2022 SIGTERM received, sending exit notification to peer
Sun Oct 16 02:43:33 2022 /etc/openvpn/tunnelDown.sh tun0 1500 1585 10.8.2.4 255.255.255.0 init
Sun Oct 16 02:43:33 2022 WARNING: Failed running command (--up/--down): could not execute external program
Sun Oct 16 02:43:33 2022 Exiting due to fatal error
```

**Comment by almico** [comment]
Transmission Openvpn
Current version: 4.0-v28

```
Mon Oct 17 10:22:17 2022 [somevpn.org] Inactivity timeout (--ping-restart), restarting
Mon Oct 17 10:22:17 2022 SIGTERM received, sending exit notification to peer
Mon Oct 17 10:22:18 2022 /etc/openvpn/tunnelDown.sh tun0 1500 1585 10.8.1.4 255.255.255.0 init
[08:22:18] FATAL: Tunnel down, addon restarting in 15 seconds
parse error: Expected string key before ':' at line 1, column 4
[08:22:33] ERROR: Unknown HTTP error occured
resolv.conf was restored
Sending kill signal to transmission-daemon
Waiting 5s for transmission-daemon to die
Successfuly closed transmission-daemon
Mon Oct 17 10:22:35 2022 /sbin/ip route del 7.25.11.62/32
Mon Oct 17 10:22:36 2022 /sbin/ip route del 0.0.0.0/1
Mon Oct 17 10:22:36 2022 /sbin/ip route del 128.0.0.0/1
Mon Oct 17 10:22:36 2022 Closing TUN/TAP interface
Mon Oct 17 10:22:36 2022 /sbin/ip addr del dev tun0 10.8.1.4/24
Mon Oct 17 10:22:36 2022 SIGTERM[soft,exit-with-notification] received, process exiting
```

This time, the addon died differently, but died 😄

**Comment by almico** [comment]
I see there is a new version of the add-on. Installing now 😄

**Comment by alexbelgium** [comment]
Hi, indeed it seems the container env doesn't get pulled in and I try to force it manually through trials and errors given I can't find a way to replicate it using portainer

**Comment by alexbelgium** [comment]
No more errors but not working anyway ;)

**Comment by almico** [comment]
Transmission Openvpn
Current version: 4.0-v27

```
Wed Oct 19 09:05:59 2022 Connection reset command was pushed by server ('[N]')
Wed Oct 19 09:05:59 2022 SIGTERM received, sending exit notification to peer
Wed Oct 19 09:06:00 2022 /etc/openvpn/tunnelDown.sh tun0 1500 1585 10.8.3.3 255.255.255.0 init
[07:06:00] FATAL: Tunnel down, addon restarting in 15 seconds
resolv.conf was restored
Sending kill signal to transmission-daemon
Waiting 5s for transmission-daemon to die
Successfuly closed transmission-daemon
Wed Oct 19 09:06:19 2022 /sbin/ip route del 4.23.15.6/32
Wed Oct 19 09:06:19 2022 /sbin/ip route del 0.0.0.0/1
Wed Oct 19 09:06:19 2022 /sbin/ip route del 128.0.0.0/1
Wed Oct 19 09:06:19 2022 Closing TUN/TAP interface
Wed Oct 19 09:06:19 2022 /sbin/ip addr del dev tun0 10.8.3.3/24
Wed Oct 19 09:06:19 2022 SIGTERM[soft,exit-with-notification] received, process exiting
```

Basically, it looks like transmission-daemon is taken down, but never started again.

**Comment by alexbelgium** [comment]
It also looks as if the curl command for the supervisor restart of the addon doesn't work ;-)

Another solution could be to link the finish script with the start one but the it would be an endless loop

**Comment by almico** [comment]
> It also looks as if the curl command for the supervisor restart of the addon doesn't work ;-)

Do you have the command, and the error?
Can I find them somewhere?

**Comment by alexbelgium** [comment]
Hi, the `bashio::addon.restart` function is described in this library : https://github.com/hassio-addons/bashio/blob/main/lib/addons.sh

If we follow the different logic, it seems to arrive to this command : `curl --silent --show-error \
        --write-out '\n%{http_code}' --request "${method}" \
        -H "${auth_header}" \
        -H "Content-Type: application/json" \
        -d "${data}" \
        "${__BASHIO_SUPERVISOR_API}${resource}"`
where $method = POST ; $resource=/addons/transmission_openvpn/restart ; $auth_header, $__BASHIO_SUPERVISOR_API are described in the container env

**Comment by almico** [comment]
> It also looks as if the curl command for the supervisor restart of the addon doesn't work ;-)

To be honest, this is something I saw in previous reports. Now, I can no longer see any trace of that [in my report](https://github.com/alexbelgium/hassio-addons/issues/435#issuecomment-1283590275).

**Comment by almico** [comment]
As far as I can see, the failure pattern is always the same now:

```
Wed Oct 19 09:05:59 2022 Connection reset command was pushed by server ('[N]')
Wed Oct 19 09:05:59 2022 SIGTERM received, sending exit notification to peer
Wed Oct 19 09:06:00 2022 /etc/openvpn/tunnelDown.sh tun0 1500 1585 10.8.3.3 255.255.255.0 init
[07:06:00] FATAL: Tunnel down, addon restarting in 15 seconds
resolv.conf was restored
Sending kill signal to transmission-daemon
Waiting 5s for transmission-daemon to die
Successfuly closed transmission-daemon
Wed Oct 19 09:06:19 2022 /sbin/ip route del 4.23.15.6/32
Wed Oct 19 09:06:19 2022 /sbin/ip route del 0.0.0.0/1
Wed Oct 19 09:06:19 2022 /sbin/ip route del 128.0.0.0/1
Wed Oct 19 09:06:19 2022 Closing TUN/TAP interface
Wed Oct 19 09:06:19 2022 /sbin/ip addr del dev tun0 10.8.3.3/24
Wed Oct 19 09:06:19 2022 SIGTERM[soft,exit-with-notification] received, process exiting
```

In the log above, I do not see any message about "Restarting Transmission daemon". I would expect something like that, since there is a "Sending kill signal to transmission-daemon".

**Comment by almico** [comment]
New error message in logs, this time!

```
Tue Oct 25 18:54:27 2022 [somevpn.org] Inactivity timeout (--ping-restart), restarting
Tue Oct 25 18:54:27 2022 SIGTERM received, sending exit notification to peer
Tue Oct 25 18:54:29 2022 /etc/openvpn/tunnelDown.sh tun0 1500 1585 10.8.0.3 255.255.255.0 init
/etc/openvpn/tunnelDown.sh: /./usr/bin/restart_addon: /usr/bin/with-contenv: bad interpreter: No such file or directory
resolv.conf was restored
Sending kill signal to transmission-daemon
Waiting 5s for transmission-daemon to die
Successfuly closed transmission-daemon
Tue Oct 25 18:54:33 2022 /sbin/ip route del 6.23.1.12/32
Tue Oct 25 18:54:33 2022 /sbin/ip route del 0.0.0.0/1
Tue Oct 25 18:54:33 2022 /sbin/ip route del 128.0.0.0/1
Tue Oct 25 18:54:33 2022 Closing TUN/TAP interface
Tue Oct 25 18:54:33 2022 /sbin/ip addr del dev tun0 10.8.0.3/24
Tue Oct 25 18:54:33 2022 SIGTERM[soft,exit-with-notification] received, process exiting
```

**Comment by almico** [comment]
Hi again @alexbelgium 😃 
So, it all boils down to this

`/./usr/bin/restart_addon: /usr/bin/with-contenv: bad interpreter: No such file or directory`

where the key point is that `/usr/bin/with-contenv` does not exist anywhere in the system.

**Comment by alexbelgium** [comment]
Thanks, I'll put back the previous one, but it still won't solve why the bashio command to restart the add-on doesn't work...

**Comment by alexbelgium** [comment]
Commit to restore the shebang : https://github.com/alexbelgium/hassio-addons/commit/72bd04aa30b2e3a431412c777a333e68b1a20b8a

**Comment by almico** [comment]
We're back to the old version of the issue 😭 

```
Thu Nov  3 09:00:35 2022 [somevpn.org] Inactivity timeout (--ping-restart), restarting
Thu Nov  3 09:00:35 2022 SIGTERM received, sending exit notification to peer
Thu Nov  3 09:00:36 2022 /etc/openvpn/tunnelDown.sh tun0 1500 1585 10.8.3.2 255.255.255.0 init
[08:00:36] FATAL: Tunnel down, addon restarting in 15 seconds
resolv.conf was restored
Sending kill signal to transmission-daemon
Waiting 5s for transmission-daemon to die
Successfuly closed transmission-daemon
Thu Nov  3 09:00:55 2022 /sbin/ip route del 9.23.11.2/32
Thu Nov  3 09:00:55 2022 /sbin/ip route del 0.0.0.0/1
Thu Nov  3 09:00:55 2022 /sbin/ip route del 128.0.0.0/1
Thu Nov  3 09:00:55 2022 Closing TUN/TAP interface
Thu Nov  3 09:00:55 2022 /sbin/ip addr del dev tun0 10.8.3.2/24
Thu Nov  3 09:00:55 2022 SIGTERM[soft,exit-with-notification] received, process exiting
```

**Comment by alexbelgium** [comment]
Ah, ah, I see you are persistent with this issue. I'm really sorry that I don't know how to solve this. Perhaps I could add a local ping with cron but I fear the impact on the addon resources

**Comment by alexbelgium** [comment]
Hi, if you activate the new auto_restart bool, it should check every hour if the vpn is up. If not, it should automatically restart the addon. Could you please try? Thanks

**Comment by almico** [comment]
It doesn't work:

```
Updating variables
Using PUID 1000 and PGID 1000
[13:01:37] INFO: Custom openvpn provider selected
Copying ovpn file to proper location
Exporting variable for custom provider : somevpn.org
[13:01:37] INFO: Auto restarting addon if openvpn down for more than 1h
chmod: cannot access '/etc/cron.hourly/cronupdate': No such file or directory
/etc/cont-init.d/99-run.sh: exiting 1
```

**Comment by alexbelgium** [comment]
New version pushed to have the log show in addon log

**Comment by alexbelgium** [comment]
Doesn't work, same error

**Comment by alexbelgium** [comment]
I think it now works. I've pushed a new version

**Comment by almico** [comment]
Installing `4.0-v40` now 😃

**Comment by almico** [comment]
Ah ah ah 😆 Then, I will install `4.0-v41`!

**Comment by alexbelgium** [comment]
Both have the same code but 41 has an additional message to say after rebooting that it was rebooted

**Comment by almico** [comment]
Yesterday, things looked promising.
Today, with 4.2-3, I'm consistently getting this:

```
[09:28:16] INFO: Starting app
Starting container with revision: f9cb4dea2da1a3aa63bd3945e0162c9b8a9789a4
Using OpenVPN provider: SOMEVPN
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for SOMEVPN. Defaulting to external config
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.E0S62k4KHK
Extracting configs to /tmp/tmp2
ERROR: Could not find any configs for provider SOMEVPN in downloaded configs
Cleanup: deleting /tmp/tmp.E0S62k4KHK and /tmp/tmp2
```

And nothing else appears in the logs (and Transmission doesn't start either).

**Comment by alexbelgium** [comment]
Hi, solved in latest version

**Comment by almico** [comment]
Installing now 😃

**Comment by almico** [comment]
Yes, it started properly, this time 😃
