### ISSUE TITLE
🐛 [SEAFILE] Error: Failed to prepare seahub avatars dir: [Errno 95] Operation not supported: '../../../seahub-data/avatars' -> '/opt/seafile/seafile-server-9.0.8/seahub/media/avatars'

### ISSUE THREAD

**Issue by bobloadmire** [alexbelgium/hassio-addons#475]
seafile

- Addon name :seafile
- Addon version :9.0.8

**Describe the bug**

possibly related to my nextcloud bug, it does write some files to my network share successfully, but then throws "Error: Failed to prepare seahub avatars dir: [Errno 95] Operation not supported: '../../../seahub-data/avatars' -> '/opt/seafile/seafile-server-9.0.8/seahub/media/avatars'
/etc/cont-init.d/99-run.sh: exiting 1"

in the log. Not sure why.

To Reproduce

1. sucessfully mount network share
2.  Seafile writes some files to network share
3. 3. then throws Error: Failed to prepare seahub avatars dir: [Errno 95] Operation not supported: '../../../seahub-data/avatars' -> '/opt/seafile/seafile-server-9.0.8/seahub/media/avatars'
/etc/cont-init.d/99-run.sh: exiting 1

**Full addon log**

2022-09-12T17:12:41+02:00 [Entrypoint] Adjusting identifiers
2022-09-12T17:12:41+02:00 [Entrypoint] No config found. Running init script
2022-09-12T17:12:41+02:00 [Init] Setting default environment
2022-09-12T17:12:41+02:00 [Init] Using MySQL/MariaDB setup
2022-09-12T17:12:41+02:00 [Init] Auto mode detected
2022-09-12T17:12:41+02:00 [Init] Waiting for db
2022-09-12T17:12:41+02:00 [Init] Exposing media folder in the volume
2022-09-12T17:12:48+02:00 [Init] Running installation script
Checking python on this machine ...

verifying password of user service ...  done

---------------------------------
This is your configuration
---------------------------------

    server name:            seafile
    server ip/domain:       127.0.0.1

    seafile data dir:       /opt/seafile/seafile-data
    fileserver port:        8082

    database:               create new
    ccnet database:         ccnet_db
    seafile database:       seafile_db
    seahub database:        seahub_db
    database user:          service

Generating ccnet configuration ...

Generating seafile configuration ...

done
Generating seahub configuration ...

----------------------------------------
Now creating ccnet database tables ...

----------------------------------------
----------------------------------------
Now creating seafile database tables ...

----------------------------------------
----------------------------------------
Now creating seahub database tables ...

----------------------------------------

Error: Failed to init seahub database: Table 'abuse_reports_abusereport' already exists
2022-09-12T17:12:48+02:00 [Init] Installation failed. Maybe the db wasn't really ready?
2022-09-12T17:12:48+02:00 [Init] Cleaning failed configuration
2022-09-12T17:12:48+02:00 [Init] Waiting for db... again
2022-09-12T17:12:49+02:00 [Init] Cleaning old databases
2022-09-12T17:12:54+02:00 [Init] Retrying install
Checking python on this machine ...

verifying password of user service ...  done

---------------------------------
This is your configuration
---------------------------------

    server name:            seafile
    server ip/domain:       127.0.0.1

    seafile data dir:       /opt/seafile/seafile-data
    fileserver port:        8082

    database:               create new
    ccnet database:         ccnet_db
    seafile database:       seafile_db
    seahub database:        seahub_db
    database user:          service

Generating ccnet configuration ...

Generating seafile configuration ...

done
Generating seahub configuration ...

----------------------------------------
Now creating ccnet database tables ...

----------------------------------------
----------------------------------------
Now creating seafile database tables ...

----------------------------------------
----------------------------------------
Now creating seahub database tables ...

----------------------------------------

Error: Failed to prepare seahub avatars dir: [Errno 95] Operation not supported: '../../../seahub-data/avatars' -> '/opt/seafile/seafile-server-9.0.8/seahub/media/avatars'
/etc/cont-init.d/99-run.sh: exiting 1

**Full addon config**

PGID: 1050
PUID: 1050
SEAFILE_ADMIN_EMAIL: bobloadmire@gmail.com
SEAFILE_ADMIN_PASSWORD: REDACTED
TZ: Europe/Paris
URL: sf.REDACTED.com
data_location: /mnt/seafile
database: mariadb_addon
networkdisks: //192.168.0.116/i/seafile
cifsusername: REDACTED
cifspassword: REDACTED

**Comment by alexbelgium** [comment]
Mmh I can't replicate. With uid and guid at 0 it doesn't work, but with both at 1000 it starts fine

**Comment by bobloadmire** [comment]
I triedn changing mine from 1050 to 1000, same error

**Comment by bobloadmire** [comment]
I just noticed my post somehow didn't have my log and config in it, swear I added it. Hold on.

**Comment by alexbelgium** [comment]
Correction: for me it works only if the data folder is on the sd (like /share), not yet with a folder on a mounted disk. I'll check

**Comment by alexbelgium** [comment]
I can replicate, and am trying to find a solution. Key issue is that it seems all folders location are customizable except for /media :)

**Comment by alexbelgium** [comment]
Could you please test last pushed version? Thanks

**Comment by bobloadmire** [comment]
version v9.0.8-2 that says don't update? lol

**Comment by alexbelgium** [comment]
Mmh indeed v9.0.8-2, I'll remove the recommendation not to update

**Comment by bobloadmire** [comment]
Ok, better, but now i'm getting 

Seafile server started
Done.
LC_ALL is not set in ENV, set to en_US.UTF-8
./seafile-server-latest/seahub.sh: line 235: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
Starting seahub at port 8000 ...
----------------------------------------
It's the first time you start the seafile server. Now let's create the admin account
----------------------------------------
What is the email for the admin account?
[ admin email ] 
Error happened during creating seafile admin.
Seahub is started
Done.
2022-09-16T23:42:29+02:00 [Launch] Done
2022-09-16T23:42:29+02:00 [Entrypoint] Waiting for termination

in the logs, and when going to the port 8000 webpage i get: 

Page unavailable
Sorry, but the requested page is unavailable due to a server hiccup.

Our engineers have been notified, so check back later.

**Comment by alexbelgium** [comment]
Have you waited a bit and it still doesn't load? On my system I get to the password screen...

**Comment by alexbelgium** [comment]
I confirm that one 3 different folders including a mounted one, I get "Successfully created seafile admin"
