### ISSUE TITLE
✨ [REQUEST] Omada: add option for older versions (V3.2)

### ISSUE THREAD

**Issue by andynbaker** [alexbelgium/hassio-addons#488]
**Which addon?**

Omada

**Is your feature request related to a problem? Please describe.**

 The version of Omada-Controller that you have here in your add-on repository is v5.5. However, TP-Link still releases updates for the older version of their controller software (now on V3.2) to support their older hardware. The mbently docker images for V3.2 are still actively maintained along side the current V5.5 image that I think is referenced by this addon. 

I'm using the older TP-Link access points so I can only run version 3.2 of the controller. As far as I can tell, this add-on cannot be configured to install version 3.2, only the latest version 5.5. I also can't find any other add-on that supports V3.2.

**Describe the solution you'd like**

Is it possible to configure this add-on to have an option to install either V3.2 or V5.5? Could there be some configuration option that then dictates which image gets pulled from the mbently repository?

**Describe alternatives you've considered**

I may try to hack this one out on my own. I just have no idea what I'm doing!

**Comment by alexbelgium** [comment]
Hi, duplicating the addon will be super easy... But I won't be able to make one for each of omada's versions... 3 and 5 are the best?

**Comment by andynbaker** [comment]
OMG that would be amazing! I just wasted an hour poking around trying to make it work and I'm completely lost. Yes, V3.2 (different from V3.1 and V3.0) and V5.X are I think the two leading version that cover all hardware on the market. You already have  V5 covered by trailing the latest mbently build. So I think you'd only need to offer V3.2 as well.

**Comment by alexbelgium** [comment]
Addon is pushed, please let me know if it works!

**Comment by andynbaker** [comment]
You da man! I'll let you know how it goes.

**Comment by andynbaker** [comment]
Check this out:

![image](https://user-images.githubusercontent.com/53503316/192000154-0dd58ac5-dd0f-4aea-bbca-114d267730e5.png)

**Comment by alexbelgium** [comment]
It's coming, the image is building. Please refresh your repo, and it should be good with v3.2 in less than 15 min

**Comment by andynbaker** [comment]
OK, first thank you so much for helping out with this (I sent a beer your way)! Second, no need to hash this out today if you don't have time. I can't get the container to finish starting. I hit start and it begins to churn, but eventually it times out and the web interface never comes up. Here's what I see in the logs:

```
-----------------------------------------------------------
 Add-on: Omada v3.2
 TP-Link Omada Controller
-----------------------------------------------------------
 Add-on version: 3.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.0  (amd64 / generic-x86-64)
 Home Assistant Core: 2022.9.6
 Home Assistant Supervisor: 2022.09.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
Creating directory
Updating permissions
Removing previous directories
rm: cannot remove '/opt/tplink/EAPController/data/html': No such file or directory
rm: cannot remove '/opt/tplink/EAPController/data/pdf': No such file or directory
Creating symlink
INFO: Validating user/group (omada:omada) exists with correct UID/GID (508:508)
INFO: Group (omada) doesn't exist; creating
INFO: User (omada) doesn't exist; creating
INFO: Time zone set to 'America/Chicago'
WARN: ownership not set correctly on '/opt/tplink/EAPController/data'; setting correct ownership (omada:omada)
WARN: ownership not set correctly on '/opt/tplink/EAPController/logs'; setting correct ownership (omada:omada)
WARN: ownership not set correctly on '/opt/tplink/EAPController/work'; setting correct ownership (omada:omada)
INFO: Starting Omada Controller as user omada
SLF4J: com.tp_link.eap.util.m.a
SLF4J: The following set of substitute loggers may have been accessed
SLF4J: during the initialization phase. Logging calls during this
SLF4J: phase were not honored. However, subsequent logging calls to these
SLF4J: loggers will work as normally expected.
SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger
SLF4J: com.tp_link.eap.start.b.a.a
SLF4J: com.tp_link.eap.start.a
SLF4J: com.tp_link.eap.configuration.b
SLF4J: com.tp_link.eap.configuration.b
SLF4J: com.tp_link.eap.configuration.b
SLF4J: com.tp_link.eap.configuration.b
SLF4J: com.tp_link.eap.configuration.b
SLF4J: com.tp_link.eap.configuration.Configuration
SLF4J: com.tp_link.eap.configuration.Configuration
SLF4J: com.tp_link.eap.configuration.Configuration
SLF4J: com.tp_link.eap.configuration.b
SLF4J: com.tp_link.eap.configuration.b
SLF4J: com.tp_link.eap.start.a
SLF4J: com.tp_link.eap.i.b
SLF4J: com.tp_link.eap.i.b
SLF4J: com.tp_link.eap.start.service.impl.EapInitServiceImpl
SLF4J: com.tp_link.eap.start.service.impl.EapInitServiceImpl
SLF4J: com.tp_link.eap.start.service.impl.EapInitServiceImpl
SLF4J: com.tp_link.eap.start.service.impl.EapInitServiceImpl
SLF4J: com.tp_link.eap.start.service.impl.EapInitServiceImpl
SLF4J: com.tp_link.eap.start.service.impl.EapInitServiceImpl
SLF4J: com.tp_link.eap.start.service.impl.EapInitServiceImpl
SLF4J: com.tp_link.eap.start.a
SLF4J: com.tp_link.eap.start.c.c
SLF4J: com.tp_link.eap.start.c.c
SLF4J: com.tp_link.eap.start.c.a
SLF4J: com.tp_link.eap.start.c.c
SLF4J: com.tp_link.eap.util.m.a
startup...
Sep 23, 2022 11:05:35 AM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 4.3.1.Final
Failed to start omada controller, going to exit
ShutdownHook: service stopped.
```

**Comment by alexbelgium** [comment]
Ahah, I hoped the structure was the same for both addons and that only the build link needed to be changed. Seems not. I'll check

**Comment by alexbelgium** [comment]
I've pushed a new version that start

**Comment by andynbaker** [comment]
Pulled down the latest version, but still no luck. I did notice this is the add-on directory: no matter how far I drill down, I can never get to the actual db files.

file:///home/andynbaker/Screenshots/Screenshot%20from%202022-09-23%2012-14-41.png

**Comment by andynbaker** [comment]
I pulled down the latest version (3.2-4), purged everything from /config/addon_config/omada_v3, and then reinstalled it. I no longer see the log4j stuff in the logs, and there are no longer an infinite number of db directories, but it still fails to start.

I was thinking that there could be some port conflict, but changing the mappings didn't help. I also was able to successfully spin up the container on this hardware by just migrating the stack over in portainer. The container started fine and I was able to log in and everything, but alas this made my installation 'unhealthy'. 

No need to spend any more time on this for now. I'll pester you again in a few days :)

Here's some more details if it helps. Have a great weekend!

```
-----------------------------------------------------------
 Add-on: Omada v3.2
 TP-Link Omada Controller
-----------------------------------------------------------
 Add-on version: 3.2-4
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.0  (amd64 / generic-x86-64)
 Home Assistant Core: 2022.9.6
 Home Assistant Supervisor: 2022.09.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
Creating directory
Updating permissions
Creating symlink
INFO: Validating user/group (omada:omada) exists with correct UID/GID (508:508)
INFO: Group (omada) doesn't exist; creating
INFO: User (omada) doesn't exist; creating
INFO: Time zone set to 'America/Chicago'
WARN: ownership not set correctly on '/opt/tplink/EAPController/data'; setting correct ownership (omada:omada)
WARN: ownership not set correctly on '/opt/tplink/EAPController/logs'; setting correct ownership (omada:omada)
WARN: ownership not set correctly on '/opt/tplink/EAPController/work'; setting correct ownership (omada:omada)
INFO: Starting Omada Controller as user omada
startup...
Sep 23, 2022 2:35:45 PM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 4.3.1.Final
Failed to start omada controller, going to exit
ShutdownHook: service stopped.
```
If it helps, here's a copy of my system information:

```
## System Information

version | core-2022.9.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.67
arch | x86_64
timezone | America/Chicago
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.27.2
Stage | running
Available Repositories | 1118
Downloaded Repositories | 11

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.0
-- | --
update_channel | stable
supervisor_version | supervisor-2022.09.1
agent_version | 1.3.0
docker_version | 20.10.17
disk_total | 234.0 GB
disk_used | 34.8 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.1.3), ESPHome (2022.9.1), Network UPS Tools (0.11.0), Z-Wave JS to MQTT (0.47.0), Frigate NVR Proxy (1.3), Node-RED (13.4.0), Terminal & SSH (9.6.1), AirCast (3.4.1), InfluxDB (4.5.0), File editor (5.4.1), Samba share (10.0.0), Samba Backup (5.1.2), Portainer (2.15.1), Omada v3.2 (3.2-4)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 8
views | 9
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | September 13, 2022 at 6:56 PM
-- | --
current_recorder_run | September 23, 2022 at 9:19 AM
estimated_db_size | 648.73 MiB
database_engine | sqlite
database_version | 3.38.5

</details>
```

**Comment by alexbelgium** [comment]
Thanks! I'll check that when I get back at my pc in a couple days then

**Comment by alexbelgium** [comment]
Could you please test newly pushed version? Data is in /data within the addon, I've changed its location

**Comment by andynbaker** [comment]
It works!!!!! You did it! Thank you so much!!!

**Comment by alexbelgium** [comment]
Thanks for the feedback! Cheers
