### ISSUE TITLE
🐛 [Nextcloud] Addon fails to start fater update to 25.0.0

### ISSUE THREAD

**Issue by kulmegil** [alexbelgium/hassio-addons#519]
**Which addon?**

- Addon name : Nextcloud
- Addon version : 25.0.0

**Describe the bug**

Addon fails to start after update to 25.0.0

**To Reproduce**

**Full addon log**

```log
cont-init: info: /etc/cont-init.d/14-php exited 0
cont-init: info: running /etc/cont-init.d/15-keygen
using keys found in /data/config/keys
cont-init: info: /etc/cont-init.d/15-keygen exited 0
cont-init: info: running /etc/cont-init.d/20-permissions
cont-init: info: /etc/cont-init.d/20-permissions exited 0
cont-init: info: running /etc/cont-init.d/30-keygen.sh
[11:32:56] INFO: Using referenced ssl certificates...
... checking if referenced files exist
... adding ssl certs in files
[11:32:56] INFO: ... done
cont-init: info: /etc/cont-init.d/30-keygen.sh exited 0
cont-init: info: running /etc/cont-init.d/85-version-checks
cont-init: info: /etc/cont-init.d/85-version-checks exited 0
cont-init: info: running /etc/cont-init.d/92-local_mounts.sh
cont-init: info: /etc/cont-init.d/92-local_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/92-smb_mounts.sh
cont-init: info: /etc/cont-init.d/92-smb_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/93-config.sh
Creating folders
Updating permissions
cont-init: info: /etc/cont-init.d/93-config.sh exited 0
cont-init: info: running /etc/cont-init.d/94-install.sh
cont-init: info: /etc/cont-init.d/94-install.sh exited 0
cont-init: info: running /etc/cont-init.d/94-memcache.sh
[11:32:57] INFO: Setting data diretory: /share/nextcloud
cont-init: info: /etc/cont-init.d/94-memcache.sh exited 0
cont-init: info: running /etc/cont-init.d/99-add_packages.sh
[11:32:57] INFO: Installing additional apps :
... inotify-tools
fetch http://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
(1/1) Installing inotify-tools (3.20.11.0-r0)
Executing busybox-1.34.1-r7.trigger
OK: 318 MiB in 228 packages
cont-init: info: /etc/cont-init.d/99-add_packages.sh exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] No custom files found, skipping...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
cont-init: info: running /etc/cont-init.d/99-custom_scripts.sh
cont-init: info: /etc/cont-init.d/99-custom_scripts.sh exited 0
cont-init: info: running /etc/cont-init.d/99-elasticsearch.sh
Nextcloud is not installed - only a limited number of commands are available
Full_Text_Search option not set
cont-init: info: /etc/cont-init.d/99-elasticsearch.sh exited 0
cont-init: info: running /etc/cont-init.d/99-mariadb_discovery.sh
cont-init: info: /etc/cont-init.d/99-mariadb_discovery.sh exited 0
cont-init: info: running /etc/cont-init.d/99-ocr.sh
Nextcloud is not installed - only a limited number of commands are available
cont-init: info: /etc/cont-init.d/99-ocr.sh exited 0
cont-init: info: running /etc/cont-init.d/99-trusted_domains.sh
Nextcloud is not installed - only a limited number of commands are available
[11:32:59] INFO: Currently set trusted domains :
Nextcloud is not installed - only a limited number of commands are available
                                                                   
  There are no commands defined in the "config:system" namespace.  
                                                                   
[11:33:00] INFO: No trusted domain set yet. The first one will be set when doing initial configuration
[11:33:00] INFO: Trusted domains set in the configuration. Refreshing domains.
[11:33:00] INFO: ... removing previously added trusted domain (except for first one created)
Nextcloud is not installed - only a limited number of commands are available
                                                                   
  There are no commands defined in the "config:system" namespace.  
                                                                   
cont-init: info: /etc/cont-init.d/99-trusted_domains.sh exited 1
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun cron (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun php-fpm (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
nginx: [emerg] open() "/config/nginx/nginx.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:1
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
nginx: [emerg] open() "/config/nginx/nginx.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:1
nginx: [emerg] open() "/config/nginx/nginx.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:1
nginx: [emerg] open() "/config/nginx/nginx.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:1
nginx: [emerg] open() "/config/nginx/nginx.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:1
nginx: [emerg] open() "/config/nginx/nginx.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:1
nginx: [emerg] open() "/config/nginx/nginx.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:1
nginx: [emerg] open() "/config/nginx/nginx.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:1
nginx: [emerg] open() "/config/nginx/nginx.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:1
nginx: [emerg] open() "/config/nginx/nginx.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:1
nginx: [emerg] open() "/config/nginx/nginx.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:1
nginx: [emerg] open() "/config/nginx/nginx.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:1
nginx: [emerg] open() "/config/nginx/nginx.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:1
nginx: [emerg] open() "/config/nginx/nginx.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:1
```

**Full addon config**

```yaml
Full_Text_Search: false
OCR: false
OCRLANG: eng,pol
PGID: 1000
PUID: 1000
additional_apps: inotify-tools
certfile: fullchain.pem
data_directory: /share/nextcloud
elasticsearch_server: <ip:port>
keyfile: privkey.pem
trusted_domains: db21ed7f-nextcloud-ocr
use_own_certs: true
```

**System**

- Supervisor version: 2022.10.0 
- Host system version: 9.2

**Comment by kulmegil** [comment]
`/etc/nginx/nginx.conf` is empty 
it only contains inlude line for `/config/nginx/nginx.conf`
is this some debug stuff left behind?

**Comment by alexbelgium** [comment]
Hi, thanks very much. It's due to an upstream modification of their containers logic, I'll see to adapt it

**Comment by alexbelgium** [comment]
Hi, the new version should work fine. thanks

**Comment by kulmegil** [comment]
I ran into loop of those errors and nginx refused to start.
Even  "rebuild" or "uninstall" did not help.
```
nginx: [emerg] no "ssl_certificate" is defined for the "listen ... ssl" directive in /data/config/nginx/site-confs/default.conf:9
nginx: [emerg] no "ssl_certificate" is defined for the "listen ... ssl" directive in /data/config/nginx/site-confs/default.conf:9
nginx: [emerg] no "ssl_certificate" is defined for the "listen ... ssl" directive in /data/config/nginx/site-confs/default.conf:9
```

Had to go to Portainer and remove Nextcloud images to force it to work?
But it does work now.

**Comment by michelebossa** [comment]
@kulmegil  how do you fix ? i have the same error on SSL_CERTIFICATE

**Comment by kulmegil** [comment]
@michelebossa
I had to use [Portainer](https://github.com/alexbelgium/hassio-addons/tree/master/portainer) addon. 

0. Make sure data is backed up - including the /share/nextcloud folder
1. Stop the addon
2. Log into Portainer
3. Go to "images" section, filter by "nextcloud"
4. Remove any images
5. Rebuild addon, start it

maybe I closed it too soon. This steps should not be required.

**Comment by alexbelgium** [comment]
Indeed, not completely normal I'll check

**Comment by kulmegil** [comment]
I had restored older backup and attempted upgrade.
I had run into the same error and actually had to uninstall addon + remove old images to make it work.
Had to create new user during installation but in the end it had restored and upgraded all previous data.

Fresh installation worked without problems.

Except "use own certs" that worked on the second restart.

**Comment by alexbelgium** [comment]
Hi, I've pushed a new version that deletes the current nginx.conf and should solve the issue

**Comment by kulmegil** [comment]
Restored backup
Upgrade went smoothly!

Except now it refuses to load my own certificates, always relying on self signed one.

**Comment by michelebossa** [comment]
Me too now I have error into browser
 NET::ERR_CERT_AUTHORITY_INVALID

**Comment by alexbelgium** [comment]
Thanks both! New version pushed that should solve this :)

**Comment by kulmegil** [comment]
@alexbelgium 
Nope
I'm still getting served self signed ones.
[addon.log](https://github.com/alexbelgium/hassio-addons/files/9833603/addon.log)

**Comment by kulmegil** [comment]
I have tested 25.0.0-7 and it was:

clean install = works as expected

25.0.0-5, 25.0.0-6 => 25.0.0-7 works as expected

24.0.7 => 25.0.0-7 worked, but Nextcloud is still reporting v24.0.6

**Comment by davoloko** [comment]
Hi @alexbelgium. After last update (25.0.0-7) shows error
"s6-applyuidgid: fatal: unable to exec php7: No such file or directory"

I change the /data/config/crontabs/root file and modify php7 for php, now work fine. Could do you please change in next version?

"s6-setuidgid abc php -f /data/config/www/nextcloud/cron.php"

Thanks!

**Comment by alexbelgium** [comment]
Hi, should be good now

**Comment by m4um4u1** [comment]
Hello @alexbelgium in 25.0.0-7 after a clean install using a smb drive and using the mount as data directory im getting:

`INFO: Composer autoloader not found, unable to continue. Check the folder "3rdparty". Running "git submodule update --init" will initialize the git submodule that handles the subfolder "3rdparty".`

This also shows as html when opening in the browser.

**Comment by JiveOff** [comment]
Hey there,

This [reply](https://github.com/alexbelgium/hassio-addons/issues/519#issuecomment-1286216865) pointed out that the addon was versioned with 25.x but the NC instance reports 24.0.6. Is this normal behavior?

Best regards,
