### ISSUE TITLE
[Paperless NG} sqlite3.OperationalError: no such table: auth_user

### ISSUE THREAD

**Issue by cablesky** [alexbelgium/hassio-addons#544]
No matter what I enter in the config.yaml - it is ignored. It is also not possible to log on to the web interface with admin/admin (or the user entered in config.yaml).

[20:21:40] INFO: Defining variables
Starting...
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Paperless NGX
 scan, index and archive all your physical documents
-----------------------------------------------------------
 Add-on version: 1.9.2-2
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (amd64 / qemux86-64)
 Home Assistant Core: 2022.11.2
 Home Assistant Supervisor: 2022.10.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
/etc/cont-init.d/20-folders.sh: executing
Creating /config/addons_config/paperless_ng
/etc/cont-init.d/90-config_yaml.sh: executing
Using config file found in /config/paperless_ng/config.yaml
Config file is a valid yaml
[20:21:41] INFO: Starting the app with the variables in /config/paperless_ng/config.yaml
PAPERLESS_OCR_LANGUAGE=DEU
PAPERLESS_OCR_MODE=redo
PAPERLESS_CONSUMPTION_DIR=/share/paperless/consumption
PAPERLESS_DATA_DIR=/share/paperless/data
PAPERLESS_TRASH_DIR=/share/paperless/trash
PAPERLESS_MEDIA_ROOT=/share/paperless/media
PAPERLESS_STATICDIR=/share/paperless/static
PAPERLESS_LOGGING_DIR=/config/paperless_ng/log
PAPERLESS_AUTO_LOGIN_USERNAME=test
TZ=Europe/Paris
PAPERLESS_ADMIN_USER=test
PAPERLESS_ADMIN_PASSWORD=user
/etc/cont-init.d/92-local_mounts.sh: executing
/etc/cont-init.d/92-smb_mounts.sh: executing
/etc/cont-init.d/99-run.sh: executing
[20:21:42] INFO: Starting redis
[20:21:42] INFO: Creating default user
333:C 10 Nov 2022 20:21:42.881 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
333:C 10 Nov 2022 20:21:42.882 # Redis version=6.0.16, bits=64, commit=00000000, modified=0, pid=333, just started
333:C 10 Nov 2022 20:21:42.882 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
333:M 10 Nov 2022 20:21:42.885 * Running mode=standalone, port=6379.
333:M 10 Nov 2022 20:21:42.886 # Server initialized
333:M 10 Nov 2022 20:21:42.886 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
333:M 10 Nov 2022 20:21:42.888 * Ready to accept connections
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: auth_user
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/shell.py", line 127, in handle
    exec(sys.stdin.read(), globals())
  File "<string>", line 6, in <module>
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 302, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1361, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: auth_user
/etc/cont-init.d/99-run.sh: exiting 1
Paperless-ngx docker container starting...
Installing languages...
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://deb.debian.org/debian-security bullseye-security InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease

**Comment by alexbelgium** [comment]
Hi, the automatic creation of admin name with admin password should be good now

**Comment by cablesky** [comment]
Thanks very much! The user will now be created. However, the config.yaml is ignored. This means that the settings defined in config.yaml are not adopted.
e.g. the defined paths (PAPERLESS_DATA_DIR, PAPERLESS_TRASH_DIR etc.) are ignored.

**Comment by alexbelgium** [comment]
Would it work now ?

**Comment by cablesky** [comment]
Thank you for the really fast reaction!
I used the following config.yaml:

_PAPERLESS_OCR_LANGUAGE: deu
PAPERLESS_OCR_MODE: skip
PAPERLESS_CONSUMPTION_DIR: /share/paperless/consumption
PAPERLESS_DATA_DIR: /share/paperless/data
PAPERLESS_TRASH_DIR: /share/paperless/trash_
PAPERLESS_MEDIA_ROOT: /share/paperless/media
PAPERLESS_STATICDIR: /share/paperless/static
PAPERLESS_LOGGING_DIR: /share/paperless/log_

The config.yaml is stored under /config/paperless_ng/config.yaml.

The error log is:

  _Applying documents.1009_auto_20201216_2005... OK
  Applying documents.1010_auto_20210101_2159... OK
  Applying documents.1011_auto_20210101_2340... OK
  Applying documents.1012_fix_archive_files... OK
  Applying documents.1013_migrate_tag_colour... OK
  Applying documents.1014_auto_20210228_1614... OK
  Applying documents.1015_remove_null_characters... OK
  Applying documents.1016_auto_20210317_1351... OK
  Applying documents.1017_alter_savedviewfilterrule_rule_type... OK
  Applying documents.1018_alter_savedviewfilterrule_value... OK
  Applying documents.1019_uisettings... OK
  Applying documents.1019_storagepath_document_storage_path... OK
  Applying documents.1020_merge_20220518_1839... OK
  Applying documents.1021_webp_thumbnail_conversion... OK
  Applying documents.1022_paperlesstask... OK
  Applying documents.1023_add_comments... OK
  Applying documents.1024_document_original_filename... OK
  Applying documents.1025_alter_savedviewfilterrule_rule_type... OK
  Applying paperless_mail.0001_initial... OK
  Applying paperless_mail.0002_auto_20201117_1334... OK
  Applying paperless_mail.0003_auto_20201118_1940... OK
  Applying paperless_mail.0004_mailrule_order... OK
  Applying paperless_mail.0005_help_texts... OK
  Applying paperless_mail.0006_auto_20210101_2340... OK
  Applying paperless_mail.0007_auto_20210106_0138... OK
  Applying paperless_mail.0008_auto_20210516_0940... OK
  Applying paperless_mail.0009_mailrule_assign_tags... OK
  Applying paperless_mail.0010_auto_20220311_1602... OK
  Applying paperless_mail.0011_remove_mailrule_assign_tag... OK
  Applying paperless_mail.0012_alter_mailrule_assign_tags... OK
  Applying paperless_mail.0009_alter_mailrule_action_alter_mailrule_folder... OK
  Applying paperless_mail.0013_merge_20220412_1051... OK
  Applying paperless_mail.0014_alter_mailrule_action... OK
  Applying paperless_mail.0015_alter_mailrule_action... OK
  Applying sessions.0001_initial... OK
Search index out of date. Updating...
Executing /usr/local/bin/paperless_cmd.sh
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: auth_user
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/shell.py", line 127, in handle
    exec(sys.stdin.read(), globals())
  File "<string>", line 6, in <module>
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 302, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1361, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: auth_user
2022-11-12 18:56:13,219 INFO Set uid to user 0 succeeded
2022-11-12 18:56:13,223 INFO supervisord started with pid 1
2022-11-12 18:56:14,230 INFO spawned: 'consumer' with pid 632
2022-11-12 18:56:14,237 INFO spawned: 'gunicorn' with pid 633
2022-11-12 18:56:14,243 INFO spawned: 'scheduler' with pid 634
2022-11-12 18:56:15,246 INFO success: consumer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-11-12 18:56:15,247 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-11-12 18:56:15,248 INFO success: scheduler entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[2022-11-12 17:56:17 +0000] [633] [INFO] Starting gunicorn 20.1.0
[2022-11-12 17:56:17 +0000] [633] [INFO] Listening at: http://[::]:8000 (633)
[2022-11-12 17:56:17 +0000] [633] [INFO] Using worker: paperless.workers.ConfigurableWorker
[2022-11-12 17:56:17 +0000] [633] [INFO] Server is ready. Spawning workers
[2022-11-12 17:56:17,319] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /share/paperless/consumption
17:56:17 [Q] INFO Q Cluster solar-alaska-vegan-mountain starting.
17:56:17 [Q] INFO Process-1:1 ready for work at 656
17:56:17 [Q] INFO Process-1:3 pushing tasks at 658
17:56:17 [Q] INFO Process-1 guarding cluster solar-alaska-vegan-mountain
17:56:17 [Q] INFO Process-1:2 monitoring at 657
17:56:17 [Q] INFO Q Cluster solar-alaska-vegan-mountain running._

Thanks in advance for a correction :-)

**Comment by alexbelgium** [comment]
I've pushed a version with a new method of superuser creation, it should at least avoid those error messages https://github.com/alexbelgium/hassio-addons/issues/544

**Comment by alexbelgium** [comment]
Mmh config.yaml still doesn't work

**Comment by alexbelgium** [comment]
All good, was much more complex than expected

**Comment by alexbelgium** [comment]
Hi, should work now

**Comment by cablesky** [comment]
Hi! Thank you for your work - but unfortunately it still doesn't work.
The directories are now created, but the login mask looks very strange.
(look at https://ibb.co/k3f3QL0)
and the login with admin/admin doesn't work either...

**Comment by alexbelgium** [comment]
Could you please try to rename you sqlite database to sqlite2 for example and restart? To see if it creates correctly from scratch. Thanks

**Comment by cablesky** [comment]
I removed all residual data before start again.

**Comment by alexbelgium** [comment]
Mmh I deleted the folder /config/addons_config/paperless_ng, rebooted, the super user was created then I went to webui and could log in with "admin" and "admin"

Here was the relevant part of the log : ```Search index out of date. Updating...
Created superuser "admin" with provided password.
Executing /usr/local/bin/paperless_cmd.sh```

**Comment by alexbelgium** [comment]
And it was confirmed to work here to : https://github.com/alexbelgium/hassio-addons/issues/549?notification_referrer_id=NT_kwDOAqIdGbM0ODI1NDIwMzA0OjQ0MTc4NzEz#issuecomment-1314435260

**Comment by cablesky** [comment]
After updating the addon again it worked. However, the addon has an issue with the Google Backup addon. As soon as the Google addon creates a backup, the entire Homeassistant system crashes and no addons are active after a restart. You have to set up Homeassistant again. That's why I can no longer use the paperless addon. Thanks anyway for the trouble!

**Comment by cablesky** [comment]
I use an x86 system (Proxmox) with SSD drive. I will use an extra VM for paperless.

**Comment by alexbelgium** [comment]
Thanks, due to docker logic there should be no way the addon can touch HA files

**Comment by alexbelgium** [comment]
I'll close as if there is an issue with vm it who ld be something different than the initial scope
