### ISSUE TITLE
🐛 [transmission_openvpn] /./etc/openvpn/start.sh OPENVPN_OPTS: unbound variable

### ISSUE THREAD

**Issue by kmorrow429** [alexbelgium/hassio-addons#557]
**Which addon?**

- Addon name : transmission_openvpn
- Addon version : 4.2-4

**Describe the bug**

When I start the add-on in HASS OS, I get the error /./etc/openvpn/start.sh: line 321: OPENVPN_OPTS: unbound variable

**Full addon log**

Starting...
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Transmission Openvpn
 Docker container running Transmission torrent client with WebUI over an OpenVPN tunnel
-----------------------------------------------------------
 Add-on version: 4.2-4
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (amd64 / qemux86-64)
 Home Assistant Core: 2022.11.2
 Home Assistant Supervisor: 2022.10.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
/etc/cont-init.d/32-nginx_ingress.sh: executing
/etc/cont-init.d/90-dns_set.sh: executing
[16:28:50] INFO: DNS SERVERS set to 1.1.1.1 8.8.8.8 
/etc/cont-init.d/92-local_mounts.sh: executing
/etc/cont-init.d/92-smb_mounts.sh: executing
/etc/cont-init.d/99-run.sh: executing
[16:28:52] INFO: Updating transmission to v3
[16:28:52] WARNING: If your previous version was v2, remove and add torrents again
--2022-11-16 16:28:52--  https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xa37da909ae70535824d82620976b5901365c5ca1
Resolving keyserver.ubuntu.com (keyserver.ubuntu.com)... 162.213.33.8, 162.213.33.9
Connecting to keyserver.ubuntu.com (keyserver.ubuntu.com)|162.213.33.8|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1804 (1.8K) [text/plain]
Saving to: '976b5901365c5ca1.key'
     0K .                                                     100%  263M=0s
2022-11-16 16:28:52 (263 MB/s) - '976b5901365c5ca1.key' saved [1804/1804]
debconf: delaying package configuration, since apt-utils is not installed
[16:29:04] INFO: Exporting variables
DEBUG=false
DNS_server=8.8.8.8,1.1.1.1
LOCAL_NETWORK=192.168.1.0/32
OPENVPN_CONFIG=GB
OPENVPN_CUSTOM_PROVIDER=false
OPENVPN_PASSWORD=****
OPENVPN_PROVIDER=nordvpn
OPENVPN_USERNAME=****
PGID=0
PUID=0
TRANSMISSION_DOWNLOAD_DIR=/share/downloads
TRANSMISSION_HOME=/config/addons_config/transmission
TRANSMISSION_INCOMPLETE_DIR=/share/incomplete
TRANSMISSION_V3_UPDATE=true
TRANSMISSION_WATCH_DIR=/share/watch_dir
TRANSMISSION_WEB_UI=standard
Using PUID 0 and PGID 0
[16:29:19] INFO: Custom openvpn provider not selected, the provider nordvpn will be used
[16:29:20] INFO: Running userscript
-------------------------------------
Transmission will run as
-------------------------------------
User name:   root
User uid:    0
User gid:    0
-------------------------------------
[16:29:20] INFO: Starting app
Starting container with revision: f9cb4dea2da1a3aa63bd3945e0162c9b8a9789a4
Using OpenVPN provider: NORDVPN
Running with VPN_CONFIG_SOURCE auto
Provider NORDVPN has a bundled setup script. Defaulting to internal config
Executing setup script for nordvpn
INFO: OVPN: Checking curl installation
INFO: OVPN: DNS resolution ok
INFO: OVPN: ok, configurations download site reachable
INFO: OVPN: Removing existing configs in /etc/openvpn/nordvpn
Checking NORDPVN API responses
INFO: OVPN:Selecting the best server...
WARNING: OVPN: empty or invalid NORDVPN_COUNTRY (value=). Ignoring this parameter. Possible values are:AL,AR,AU,AT,BE,BA,BR,BG,CA,CL,CR,HR,CY,CZ,DK,EE,FI,FR,GE,DE,GR,HK,HU,IS,ID,IE,IL,IT,JP,LV,LT,LU,MY,MX,MD,NL,NZ,MK,NO,PL,PT,RO,RS,SG,SK,SI,ZA,KR,ES,SE,CH,TW,TH,TR,UA,AE,GB,US,VN, or Albania,Argentina,Australia,Austria,Belgium,Bosnia and Herzegovina,Brazil,Bulgaria,Canada,Chile,Costa Rica,Croatia,Cyprus,Czech Republic,Denmark,Estonia,Finland,France,Georgia,Germany,Greece,Hong Kong,Hungary,Iceland,Indonesia,Ireland,Israel,Italy,Japan,Latvia,Lithuania,Luxembourg,Malaysia,Mexico,Moldova,Netherlands,New Zealand,North Macedonia,Norway,Poland,Portugal,Romania,Serbia,Singapore,Slovakia,Slovenia,South Africa,South Korea,Spain,Sweden,Switzerland,Taiwan,Thailand,Turkey,Ukraine,United Arab Emirates,United Kingdom,United States,Vietnam,. Please check https://haugene.github.io/docker-transmission-openvpn/provider-specific/#nordvpn
WARNING: OVPN: empty or invalid NORDVPN_CATEGORY (value=). ignoring this parameter. Possible values are: legacy_double_vpn,legacy_onion_over_vpn,legacy_ultra_fast_tv,legacy_anti_ddos,legacy_dedicated_ip,legacy_standard,legacy_netflix_usa,legacy_p2p,legacy_obfuscated_servers,europe,the_americas,asia_pacific,africa_the_middle_east_and_india,anycast-dns,geo_dns,grafana,kapacitor,legacy_socks5_proxy,fastnetmon,. Please check https://haugene.github.io/docker-transmission-openvpn/provider-specific/#nordvpn
WARNING: OVPN: Empty or invalid NORDVPN_PROTOCOL (value=), expecting tcp or udp. setting to udp. Please read https://haugene.github.io/docker-transmission-openvpn/provider-specific/#nordvpn
INFO: OVPN: Best server : uk1875.nordvpn.com, load: 7
INFO: OVPN: Downloading config: uk1875.nordvpn.com.ovpn
INFO: OVPN: Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/uk1875.nordvpn.com.udp.ovpn
Starting OpenVPN using config uk1875.nordvpn.com.ovpn
Modifying /etc/openvpn/nordvpn/uk1875.nordvpn.com.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
Modification: Change ca certificate path
Modification: Change ping options
Modification: Update/set resolv-retry to 15 seconds
Modification: Change tls-crypt keyfile path
Modification: Set output verbosity to 3
Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
Modification: Updating status for config failure detection
Setting OpenVPN credentials...
adding route to local network 192.168.1.0/32 via 172.30.32.1 dev eth0
/./etc/openvpn/start.sh: line 321: OPENVPN_OPTS: unbound variable

**Full addon config**

DEBUG: false
DNS_server: 8.8.8.8,1.1.1.1
LOCAL_NETWORK: 192.168.1.0/32
OPENVPN_PASSWORD: ****
OPENVPN_USERNAME: ****
PGID: "0"
PUID: "0"
TRANSMISSION_DOWNLOAD_DIR: /share/downloads
TRANSMISSION_HOME: /config/addons_config/transmission
TRANSMISSION_INCOMPLETE_DIR: /share/incomplete
TRANSMISSION_V3_UPDATE: "true"
TRANSMISSION_WATCH_DIR: /share/watch_dir
TRANSMISSION_WEB_UI: standard
OPENVPN_PROVIDER: nordvpn
OPENVPN_CUSTOM_PROVIDER: false
OPENVPN_CONFIG: GB

**System**

- Supervisor version: 2022.10.2
- Host system version: Home Assistant OS 9.3  (amd64 / qemux86-64)

**Comment by alexbelgium** [comment]
Hi, this seems to come from upstream. I've pushed a new version to see if it makes a difference

**Comment by AlecRust** [comment]
No new version showing yet.. are you missing the "Update config.json" commit? 🙂

**Comment by kmorrow429** [comment]
Can't seem to update to the new version. Tried uninstalling the existing version, rebooting the host, then installing from scratch. But I'm still getting the below error:
Can't install ghcr.io/alexbelgium/transmission_openvpn-amd64:4.2-5: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=4.2-5&fromImage=ghcr.io%2Falexbelgium%2Ftransmission_openvpn-amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")

**Comment by alexbelgium** [comment]
Hi, indeed thanks for noticing I've pushed a new version to avoid that

**Comment by alexbelgium** [comment]
Thanks for the feedback!
