### ISSUE TITLE
🐛 [Seafile] Cannot change or download files

### ISSUE THREAD

**Issue by ElVit** [alexbelgium/hassio-addons#647]
**Which addon?**

- Addon name : Seafile
- Addon version : v9.0.14-pro

**Describe the bug**

**To Reproduce**

If I connect locally or over the configured url (over firefox, chrome, safari), I cannot change or download files.
If I try to save the file the save button just showing the loading circle.
If I try to download a file I get the error ERR_CONNECTION_REFUSED.

**Full addon log**

```
Starting...
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Seafile
 High performance file syncing and sharing, with also Markdown WYSIWYG editing, Wiki, file label and other knowledge management features
-----------------------------------------------------------
 Add-on version: v9.0.14-pro
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.4  (amd64 / generic-x86-64)
 Home Assistant Core: 2022.12.8
 Home Assistant Supervisor: 2022.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
/etc/cont-init.d/01-custom_script.sh: executing
[13:00:41] INFO: Execute /config/seafile.sh if existing
[13:00:41] INFO: ... no script found
/etc/cont-init.d/92-local_mounts.sh: executing
/etc/cont-init.d/92-smb_mounts.sh: executing
/etc/cont-init.d/99-run.sh: executing
[13:00:41] INFO: Setting variables
PGID='1000'
PUID='1000'
SEAFILE_ADMIN_EMAIL='redacted-email'
SEAFILE_ADMIN_PASSWORD=******
TZ='Europe/Berlin'
URL='redacted-url'
data_location='/share/seafile'
database='sqlite'
[13:00:44] INFO: Setting data location
... check /share/seafile folder exists
... setting permissions
... copy media files
... correcting official script
[13:00:44] INFO: Defining database
[13:00:44] INFO: Starting app
2022-12-28T13:00:44+01:00 [Entrypoint] Local time set to Europe/Berlin
2022-12-28T13:00:44+01:00 [Entrypoint] Checking permissions
2022-12-28T13:00:44+01:00 [Entrypoint] Adjusting identifiers
usermod: no changes
2022-12-28T13:00:44+01:00 [Entrypoint] Running launch script
2022-12-28T13:00:44+01:00 [Launch] Making symlink to latest version
2022-12-28T13:00:44+01:00 [Launch] Linking internal configuration and data folders with the volume
2022-12-28T13:00:44+01:00 [Launch] Waiting for db
2022-12-28T13:00:44+01:00 [Launch] Launching seafile
Starting seafile server, please wait ...
** Message: 13:00:44.794: seafile-controller.c(621): No seafevents.
Seafile server started
Done.
LC_ALL is not set in ENV, set to en_US.UTF-8
./seafile-server-latest/seahub.sh: line 236: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
Starting seahub at port 8000 ...
Seahub is started
Done.
2022-12-28T13:00:53+01:00 [Launch] Done
2022-12-28T13:00:53+01:00 [Entrypoint] Waiting for termination
```

**Full addon config**

```
PGID: 1000
PUID: 1000
SEAFILE_ADMIN_EMAIL: "!secret seafile_username"
SEAFILE_ADMIN_PASSWORD: "!secret seafile_password"
TZ: Europe/Berlin
URL: "!secret seafile_uri_1"
data_location: /share/seafile
database: sqlite
```

**System**

- Supervisor version: 2022.11.2
- Host system version: Home Assistant OS 9.4  (amd64 / generic-x86-64)

**Comment by ElVit** [comment]
Issue still present

**Comment by alexbelgium** [comment]
Hi, thanks it wasn't up to date and some config were missing. You should see two new options to configure : the server ip (your HA ip/domain) and it's port (8082 by default)

I'll build it now and test it

**Comment by alexbelgium** [comment]
Actually it doesn't seem to work. But you can change manually the server address by going top right in System Admin > Settings, and define SERVICE_URL as your ip

**Comment by alexbelgium** [comment]
I've pushed a new version where the addon options could work

**Comment by igorsantos07** [comment]
This is still present for me... I've just installed the add-on, but I'm unable to configure it properly.

My server is accessible via `http://hass.local:8123`, and thus the add-on config is as follows:
```yaml
CONFIG_LOCATION: /config/addons_config/seafile/config.yaml # nothing here but the standard comments
FILE_SERVER_ROOT: http://hass.local:8082
PGID: 1000
PORT: "8082"
PUID: 1000
SEAFILE_ADMIN_EMAIL: ***
SEAFILE_ADMIN_PASSWORD: ***
SERVER_IP: hass.local
TZ: America/Sao_Paulo
data_location: /media/backup # this is the same path I can use to access my external drive from the SSH add-on
database: sqlite
url: seafile.example.com # not really sure what this is? that's the default value
localdisks: sdb1
```

The path it generates to download a file is something like `http://hass.local/seafhttp/files/«hash/file.ext»`, but the one I got working (from trial and error) should be `http://hass.local:8082/files/«hash/file.ext»`.

I've already tried the actual IP under `SERVER_IP`, as well as adding the port or protocol. The port even shows up correctly, but nothing (not even a leading slash) could remove the `seafhttp` from the path.

**Comment by alexbelgium** [comment]
Please provide a full startup log to see what could fail
