### ISSUE TITLE
[nextcloud] mnt folder permission denied error

### ISSUE THREAD

**Issue by ug30242** [alexbelgium/hassio-addons#818]
Hi, thanks for addressing the smb mount issue a while ago. Thanks to you, I used it well, but suddenly it didn't start, so looking at the log, it seems that there is an error as below. Why is this and how to fix it?

[00:52:40] INFO: ... //192.168.0.74/Nextcloud successfully mounted to /mnt/Nextcloud with options ,vers=1.0,uid=1000,gid=1000,iocharset=utf8
cont-init: info: /etc/cont-init.d/00-smb_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/01-custom_script.sh
[00:52:40] INFO: Execute /config/addons_autoscripts/nextcloud-ocr.sh if existing
[00:52:40] INFO: ... no script found
cont-init: info: /etc/cont-init.d/01-custom_script.sh exited 0
cont-init: info: running /etc/cont-init.d/01-folders.sh
Setting user to 1000:1000
Updating permissions...
... Config directory : /data
... Data directory detected : /mnt/Nextcloud
**chmod: changing permissions of '/mnt/Nextcloud': Permission denied**

**Comment by alexbelgium** [comment]
Hi, thanks I see i'll adapt the code and push a new version tomorrow

**Comment by ug30242** [comment]
Thank you very much for your quick response! Can I apply the uploaded file to my Home Assistant before the updated version is applied?
If so, I'm sorry this is such a rudimentary question, but where is the folder path?

**Comment by ug30242** [comment]
Thanks, I updated and that error went away. However, I still can't access it, so I checked the log, and at the end it came out like this and exited. Can you help me one more time?

**cont-init: info: /etc/cont-init.d/99-trusted_domains.sh exited 0**
Setting resolver to  127.0.0.11
Setting worker_processes to 4
using keys found in /data/config/keys
Removing CODE Server
richdocumentscoderichdocumentscode_arm64 is not installed
**s6-rc: warning: unable to start service init-nextcloud-config: command exited 1**

**Comment by ug30242** [comment]
Checking again, it seems that the log below is the last one to restart over and over again. If it somehow passes this part, it goes well, then the log mentioned above comes out, and I still can't connect.


Mounting smb share(s)...
Using PUID 1000 and PGID 1000
[21:20:52] INFO: ... //192.168.0.74/Nextcloud successfully mounted to /mnt/Nextcloud with options ,vers=1.0,uid=1000,gid=1000,iocharset=utf8
cont-init: info: /etc/cont-init.d/00-smb_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/01-custom_script.sh
[21:20:52] INFO: Execute /config/addons_autoscripts/nextcloud-ocr.sh if existing
[21:20:52] INFO: ... no script found
cont-init: info: /etc/cont-init.d/01-custom_script.sh exited 0
cont-init: info: running /etc/cont-init.d/01-folders.sh
Setting user to 1000:1000
Updating permissions...
... Config directory : /data
... Data directory detected : /mnt/Nextcloud

**Comment by alexbelgium** [comment]
Strange... You could try with puid 0 and guid 0 perhaps

**Comment by alexbelgium** [comment]
I've pushed a new version to test. But after trying this could you please post your complete log. Thanks

**Comment by ug30242** [comment]
I tried applying the update, changing the puid and guid to 0, but it still doesn't work.

Certainly, this symptom appeared after I tried to change the host hardware. (Raspberry Pi 4B → dell wyse 5070 (J5005))
I made a full backup of the Raspberry Pi 4B's HA, applied the HA's fixed IP to the new hardware, and then restored it, but it didn't work properly. So, after clearing the HA of the new hardware, I returned to the original system (Raspberry Pi 4B), and since then everything else is normal, only nextcloud doesn't work.

Leave the entire log running this time below (sensitive information covered, the first part was cut off a little). I was using nextcloud for work with co-workers and I really need to restore it. Help me.


(When the puid and guid are changed to 0, only the puid and guid are changed, and it is the same log, so I will not attach it separately.)
`-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
 Defining permissions for main user : 
User UID: 1000
User GID : 1000
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/00-local_mounts.sh
cont-init: info: /etc/cont-init.d/00-local_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/00-smb_mounts.sh
Mounting smb share(s)...
Using PUID 1000 and PGID 1000
[19:43:54] INFO: ... //192.168.0.74/Nextcloud successfully mounted to /mnt/Nextcloud with options ,vers=1.0,uid=1000,gid=1000,iocharset=utf8
cont-init: info: /etc/cont-init.d/00-smb_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/01-custom_script.sh
[19:43:54] INFO: Execute /config/addons_autoscripts/nextcloud-ocr.sh if existing
[19:43:54] INFO: ... no script found
cont-init: info: /etc/cont-init.d/01-custom_script.sh exited 0
cont-init: info: running /etc/cont-init.d/01-folders.sh
Setting user to 1000:1000
Updating permissions...
... Config directory : /data
... Data directory detected : /mnt/Nextcloud
Disabling check_data_directory_permissions
System config value check_data_directory_permissions set to boolean false
...done
 
cont-init: info: /etc/cont-init.d/01-folders.sh exited 0
cont-init: info: running /etc/cont-init.d/02-init_steps.sh
Cleaning files
Setting logs
 
----------------------------------------
 Nextcloud 26.0.0 is installed 
----------------------------------------
 
cont-init: info: /etc/cont-init.d/02-init_steps.sh exited 0
cont-init: info: running /etc/cont-init.d/02-mariadb_discovery.sh
---
MariaDB addon was found! It can't be configured automatically due to the way Nextcloud works, but you can configure it manually when running the web UI for the first time using those values :
Database user : service bashio::log.blue Database user : service
Database password : OoJah1daveeLahghoopaizae4ooph7PeemohRex3cour1iw0Iphe8Nei1Eh3EJix
Database name : nextcloud
Host-name : core-mariadb:3306
---
cont-init: info: /etc/cont-init.d/02-mariadb_discovery.sh exited 0
cont-init: info: running /etc/cont-init.d/30-ssl.sh
cont-init: info: /etc/cont-init.d/30-ssl.sh exited 0
cont-init: info: running /etc/cont-init.d/98-upgrade.sh
Auto_updater set, checking for updates
Nextcloud Updater - version: v26.0.0beta2-9-g64e2e4c dirty
Step 6 is currently in process. Please call this command later.
cont-init: info: /etc/cont-init.d/98-upgrade.sh exited 255
cont-init: info: running /etc/cont-init.d/99-add_packages.sh
[19:45:19] INFO: Installing additional apps :
... inotify-tools
cont-init: info: /etc/cont-init.d/99-add_packages.sh exited 0
cont-init: info: running /etc/cont-init.d/99-elasticsearch.sh
cont-init: info: /etc/cont-init.d/99-elasticsearch.sh exited 0
cont-init: info: running /etc/cont-init.d/99-ocr.sh
cont-init: info: /etc/cont-init.d/99-ocr.sh exited 0
cont-init: info: running /etc/cont-init.d/99-trusted_domains.sh
[19:45:24] INFO: Currently set trusted domains :
_HA IP_
_HA IP_
_DDNS
DDNS_
[19:45:26] INFO: Trusted domains set in the configuration. Refreshing domains.
[19:45:26] INFO: ... removing previously added trusted domain (except for first one created)
System config value trusted_domains => 2 deleted
System config value trusted_domains => 3 deleted
System config value trusted_domains => 4 deleted
System config value trusted_domains => 5 deleted
[19:45:36] INFO: ... alignement with trusted domains list : _IP ADDRESS_
[19:45:36] INFO: ... adding _HA IP_
System config value trusted_domains => 6 set to string _HA IP_
[19:45:38] INFO: ... adding _DDNS_
System config value trusted_domains => 7 set to string _HA IP_
[19:45:40] INFO: ... adding _HA IP_
System config value trusted_domains => 8 set to string _HA IP_
[19:45:42] INFO: ... adding _DDNS_
System config value trusted_domains => 9 set to string _DDNS_
[19:45:45] INFO: Remaining configurated trusted domains :
[19:45:47] INFO: _HA IP_
_HA IP_
_DDNS_
_HA IP_
_DDNS_
cont-init: info: /etc/cont-init.d/99-trusted_domains.sh exited 0
Setting resolver to  127.0.0.11
Setting worker_processes to 4
using keys found in /data/config/keys
Removing CODE Server
richdocumentscoderichdocumentscode_arm64 is not installed
s6-rc: warning: unable to start service init-nextcloud-config: command exited 1`

**Comment by alexbelgium** [comment]
This is very interesting. Do you have the app "richdocumentscode" installed ? This seems to be the case according to your code.

`Removing CODE Server
richdocumentscoderichdocumentscode_arm64 is not installed`

This causes the issue. Not sure how to avoid that without pushing a new version

**Comment by alexbelgium** [comment]
That's the thing - when going on your dell, it probably installed amd64 versions of the apps. However going back to rpi4b it looks for the aarch64 versions which don't work

**Comment by alexbelgium** [comment]
Ahah, glad it worked! I'll add it to my code just for safe keeping in case anyone else needs it. Have a nice day
