### ISSUE TITLE
🐛 [Seafile] Can't install ghcr.io/alexbelgium/seafile-armv7:10.0.1: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=10.0.1&fromImage=ghcr.io%2Falexbelgium%2Fseafile-armv7&platform=linux%2Farm%2Fv7: Internal Server Error ("manifest unknown")

### ISSUE THREAD

**Issue by encryptix** [alexbelgium/hassio-addons#841]
**Which addon?**

- Addon name : Seafile
- Addon version : 10.0.1

**Describe the bug**

Cant install seafile, probably a similar issue to [🐛 [Filebrowser] Can't install ghcr.io/alexbelgium/filebrowser-amd64:2.23.0-6: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=2.23.0-6&fromImage=ghcr.io%2Falexbelgium%2Ffilebrowser-amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown") #834
](https://github.com/alexbelgium/hassio-addons/issues/834) ?
**To Reproduce**

1. Go to 'Add on Store'
2. Click on 'Seafile'
3. Click Install

**Full addon log**

As above

**Full addon config**

N/A

**System**

Home Assistant 
Supervisor 

- Supervisor version: 2023.04.1
- HA 2023.4.6
- Host system: 
- Host system version: Raspbian 11

**Comment by alexbelgium** [comment]
Hi, I've pushed a new version to force build. Should be good now

**Comment by encryptix** [comment]
Still not working for me but it does show 10-2 in the UI.

One thing I noticed is the tagged versions for am go to v9: https://github.com/alexbelgium/hassio-addons/pkgs/container/seafile-armv7

where aarch64 and amd64 have a few images tagged with 10 e.g. https://github.com/alexbelgium/hassio-addons/pkgs/container/seafile-amd64

**Comment by alexbelgium** [comment]
Good observation! Armv7 was disabled in build.json. There is a parallel issue about the latest builds though, so it seems they have changed something has changed I need to adapt to.

**Comment by alexbelgium** [comment]
Builds are no successful which should remove this issue : https://github.com/alexbelgium/hassio-addons/actions/runs/5041892806

**Comment by alexbelgium** [comment]
I'll close as the other issue already has a thread

**Comment by encryptix** [comment]
Thank you
