### ISSUE TITLE
🐛 [Nextcloud] <Can't start the add-on>

### ISSUE THREAD

**Issue by hoanglongutc** [alexbelgium/hassio-addons#911]
### Description

After updating Nextcloud 27.0.1-2 I can't start the add-on

### Reproduction steps

```bash
Cleaning files
Creating possible missing Directories
s6-rc: warning: unable to start service init-adduser: command exited 1
```

### Addon Logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done

-----------------------------------------------------------
 Add-on: Nextcloud
 Nextcloud for Home Assistant
-----------------------------------------------------------
 Add-on version: 27.0.1-2
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (amd64 / qemux86-64)
 Home Assistant Core: 2023.7.3
 Home Assistant Supervisor: 2023.07.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
 Defining permissions for main user : 
User UID: 1000
User GID : 1000
-----------------------------------------------------------
Cleaning files
Creating possible missing Directories
s6-rc: warning: unable to start service init-adduser: command exited 1
```

### Architecture

amd64

### OS

Virtual Machine

**Comment by alexbelgium** [comment]
Hi, I've pushed a version with more streamline code for the part that seems problematic, could you please test ? I can't replicate on my systems. Thanks

Btw - are you sure you migrated to nextcloud 27 ? The linuxserver logic (image my addon is based on) strictly requires an up-to-date nextcloud before updating or it will fail and be quite complex to solve. Thanks!

**Comment by dd310** [comment]
I was encountering the same problem, and with the lastest version (27.0.1-6) everything is working again 👍

**Comment by hoanglongutc** [comment]
> Hi, I've pushed a version with more streamline code for the part that seems problematic, could you please test ? I can't replicate on my systems. Thanks
> 
> Btw - are you sure you migrated to nextcloud 27 ? The linuxserver logic (image my addon is based on) strictly requires an up-to-date nextcloud before updating or it will fail and be quite complex to solve. Thanks!

I upgraded but still can't start the add-on, I'm trying to uninstall and reinstall

**Comment by hoanglongutc** [comment]
> Hi, I've pushed a version with more streamline code for the part that seems problematic, could you please test ? I can't replicate on my systems. Thanks
> 
> Btw - are you sure you migrated to nextcloud 27 ? The linuxserver logic (image my addon is based on) strictly requires an up-to-date nextcloud before updating or it will fail and be quite complex to solve. Thanks!

I tried reinstalling the add-on, but still get the following error:
Cleaning files
Creating possible missing Directories
chmod Files and Directories. This could take some time, please wait...
chown Directories. This could take some time, please wait...
chmod: cannot access '/data/config/www/nextcloud/occ': No such file or directory
s6-rc: warning: unable to start service init-adduser: command exited 1

**Comment by alexbelgium** [comment]
On which version? Sorry guys this is a major code changed forced by the upstream container. I can't replicate on haos but I think it is more la on resuming in case of errors

**Comment by hoanglongutc** [comment]
> On which version? Sorry guys this is a major code changed forced by the upstream container. I can't replicate on haos but I think it is more la on resuming in case of errors

I just installed version: 27.0.1-6

**Comment by hoanglongutc** [comment]
> On which version? Sorry guys this is a major code changed forced by the upstream container. I can't replicate on haos but I think it is more la on resuming in case of errors

Everything is working again, many thanks

**Comment by Ovenlade** [comment]
I had the same error when updating to 27.0.1-2 but everything is working again after updating to 27.0.1-7. Thanks for the quick fix!

**Comment by alexbelgium** [comment]
Then I'll close it. Thanks!
